import { NextRequest, NextResponse } from "next/server";
import { Storage } from "@google-cloud/storage";

const storage = new Storage({
  projectId: process.env.GCP_PROJECT_ID,
  // On Cloud Run, uses the service account automatically
});

const BUCKET_NAME = process.env.GCS_BUCKET_NAME || "climaguard-reports";

export async function POST(req: NextRequest) {
  try {
    const { country, childName, childAge, overallRisk, analysis, weather, language } = await req.json();

    // Build plain-text PDF content (no binary fonts needed server-side)
    const lines = [
      "CLIMAGUARD CHILD CLIMATE RISK REPORT",
      "=====================================",
      "",
      `Date: ${new Date().toLocaleDateString("en-GB")}`,
      `Location: ${country}`,
      `Child: ${childName || "Child"}, Age ${childAge}`,
      `Language: ${language}`,
      `Overall Risk: ${overallRisk}`,
      "",
      "WEATHER CONDITIONS",
      "------------------",
      `Temperature: ${weather.temperature}°C`,
      `Humidity: ${weather.humidity}%`,
      `Wind Speed: ${weather.wind_speed} km/h`,
      `UV Index: ${weather.uv_index}`,
      `Air Quality: ${weather.air_quality_index ? `AQI ${weather.air_quality_index}` : "N/A"}`,
      "",
      "ACTIVE HAZARDS",
      "--------------",
      ...(weather.hazards || []).map((h: { type: string; severity: string; description: string }) =>
        `[${h.severity}] ${h.type}: ${h.description}`
      ),
      "",
      "AI ACTION PLAN",
      "--------------",
      analysis,
      "",
      "---",
      "Generated by ClimaGuard — Powered by Google Gemini API",
      "Not a substitute for professional medical advice.",
    ];

    const content = lines.join("\n");
    const fileName = `reports/${Date.now()}-${(childName || "child").replace(/\s+/g, "-")}.txt`;

    try {
      const bucket = storage.bucket(BUCKET_NAME);
      const file = bucket.file(fileName);
      await file.save(content, { contentType: "text/plain; charset=utf-8" });
      const [url] = await file.getSignedUrl({
        action: "read",
        expires: Date.now() + 24 * 60 * 60 * 1000, // 24 hours
      });
      return NextResponse.json({ url, fileName });
    } catch (storageError) {
      // Cloud Storage not configured — fall back to inline download
      const base64 = Buffer.from(content).toString("base64");
      const dataUrl = `data:text/plain;base64,${base64}`;
      return NextResponse.json({ url: dataUrl, fallback: true });
    }
  } catch (error) {
    console.error("PDF export error:", error);
    return NextResponse.json({ error: "Failed to export report" }, { status: 500 });
  }
}
