// AUTO-GENERATED profile-page translations (Gemini 2.5 Flash).
import type { ProfileStrings } from "./profileStrings";

export const PROFILE_STRINGS_AUTO: Record<string, ProfileStrings> = {
  "yo": {
    "backHome": "Sẹ́hìn",
    "intro": "Ṣètò ọmọ kọ̀ọ̀kan lẹ́ẹ̀kan — ọjọ́ orí, ibi, àti èdè. Ọmọ tó wà ní ìlò yóò mú gbogbo ohun èlò jẹ́ ti ara ẹni. Tí a fipamọ́ sínú ẹ̀rọ rẹ tí a sì mú bá àwọn ẹ̀rọ mìíràn mu.",
    "syncing": "ń mú bá ara mu…",
    "addChild": "Fi ọmọ kún",
    "noChildren": "Kò sí ọmọ tí a fi kún síbẹ̀ — ohun èlò náà ṣì ń ṣiṣẹ́. Fi ọmọ kún láti mú gbogbo ohun èlò jẹ́ ti ara ẹni.",
    "active": "Ní ìlò",
    "setActive": "Ṣètò sí ìlò",
    "edit": "Ṣatunṣe",
    "remove": "Yọ kúrò",
    "editTitle": "Ṣatunṣe ọmọ",
    "nameLabel": "Orúkọ ọmọ",
    "healthLabel": "Àwọn ìṣòro ìlera",
    "optional": "ìyàn",
    "save": "Fipamọ́",
    "addBtn": "Fi ọmọ kún",
    "cancel": "Fagilé",
    "underOne": "Lábẹ́ ọdún 1",
    "years": "ọdún",
    "checkDangerFor": "Ṣàyẹ̀wò ewu fún"
  },
  "ig": {
    "backHome": "Azụ",
    "intro": "Hazie nwa ọ bụla otu ugboro — afọ, ebe, na asụsụ. Nwa ahụ na-arụ ọrụ na-eme ka ngwa ọ bụla bụrụ nke ya. Echekwara na ngwaọrụ gị ma mekọrịta ya na ngwaọrụ ndị ọzọ.",
    "syncing": "na-emekọrịta…",
    "addChild": "Tinye nwa",
    "noChildren": "Etinyebeghị ụmụaka — ngwa ahụ ka na-arụ ọrụ. Tinye nwa ka ngwa ọ bụla bụrụ nke gị.",
    "active": "Na-arụ ọrụ",
    "setActive": "Mee ka ọ rụọ ọrụ",
    "edit": "Dezie",
    "remove": "Wepụ",
    "editTitle": "Dezie nwa",
    "nameLabel": "Aha nwa",
    "healthLabel": "Nsogbu ahụike",
    "optional": "nhọrọ",
    "save": "Chekwaa",
    "addBtn": "Tinye nwa",
    "cancel": "Kagbuo",
    "underOne": "N'okpuru afọ 1",
    "years": "afọ",
    "checkDangerFor": "Lelee ihe egwu maka"
  },
  "zu": {
    "backHome": "Emuva",
    "intro": "Setha ingane ngayinye kanye — iminyaka, indawo, nolimi. Ingane esebenzayo yenza ithuluzi ngalinye libe ngelakho. Igcineka kudivayisi yakho futhi ivumelaniswa kuwo wonke amadivayisi.",
    "syncing": "iyavumelanisa…",
    "addChild": "Engeza ingane",
    "noChildren": "Azikho izingane ezingeziwe okwamanje — uhlelo lokusebenza lusasebenza. Engeza ingane ukuze wenze wonke amathuluzi abe ngawena.",
    "active": "Esebenzayo",
    "setActive": "Yenza isebenze",
    "edit": "Hlela",
    "remove": "Susa",
    "editTitle": "Hlela ingane",
    "nameLabel": "Igama lengane",
    "healthLabel": "Izinkinga zempilo",
    "optional": "Ongakukhetha",
    "save": "Gcina",
    "addBtn": "Engeza ingane",
    "cancel": "Khansela",
    "underOne": "Ngaphansi konyaka ongu-1",
    "years": "iminyaka",
    "checkDangerFor": "Hlola ingozi ka"
  },
  "af": {
    "backHome": "Terug",
    "intro": "Stel elke kind een keer op — ouderdom, plek en taal. Die aktiewe kind verpersoonlik elke hulpmiddel. Gestoor op jou toestel en gesinkroniseer oor toestelle heen.",
    "syncing": "sinkroniseer…",
    "addChild": "Voeg 'n kind by",
    "noChildren": "Nog geen kinders bygevoeg nie — die toepassing werk steeds. Voeg 'n kind by om elke hulpmiddel persoonlik te maak.",
    "active": "Aktief",
    "setActive": "Stel aktief",
    "edit": "Wysig",
    "remove": "Verwyder",
    "editTitle": "Wysig kind",
    "nameLabel": "Kind se naam",
    "healthLabel": "Gesondheidsprobleme",
    "optional": "opsioneel",
    "save": "Stoor",
    "addBtn": "Voeg kind by",
    "cancel": "Kanselleer",
    "underOne": "Onder 1 jaar",
    "years": "jaar",
    "checkDangerFor": "Kontroleer gevaar vir"
  },
  "mg": {
    "backHome": "Miverina",
    "intro": "Amboary indray mandeha isaky ny zaza — taona, toerana, ary fiteny. Ny zaza mavitrika no manokana ny fitaovana rehetra. Voatahiry ao amin'ny fitaovanao ary mifandrindra amin'ny fitaovana hafa.",
    "syncing": "mifandrindra…",
    "addChild": "Manampy zaza",
    "noChildren": "Tsy mbola nisy zaza nampiana — mbola miasa ihany ny fampiharana. Manampia zaza mba hahatonga ny fitaovana rehetra ho manokana.",
    "active": "Mavitrika",
    "setActive": "Ataovy mavitrika",
    "edit": "Hanova",
    "remove": "Esory",
    "editTitle": "Hanova zaza",
    "nameLabel": "Anaran'ny zaza",
    "healthLabel": "Olana ara-pahasalamana",
    "optional": "tsy voatery",
    "save": "Tehirizo",
    "addBtn": "Manampy zaza",
    "cancel": "Hanafoana",
    "underOne": "Latsaky ny 1 taona",
    "years": "taona",
    "checkDangerFor": "Jereo ny loza ho an'ny"
  },
  "ms": {
    "backHome": "Kembali",
    "intro": "Sediakan setiap anak sekali — umur, tempat, dan bahasa. Anak yang aktif memperibadikan setiap alat. Disimpan pada peranti anda dan disegerakkan merentasi peranti.",
    "syncing": "Menyegerakkan…",
    "addChild": "Tambah anak",
    "noChildren": "Tiada anak ditambahkan lagi — aplikasi masih berfungsi. Tambah anak untuk menjadikan setiap alat peribadi.",
    "active": "Aktif",
    "setActive": "Tetapkan aktif",
    "edit": "Sunting",
    "remove": "Buang",
    "editTitle": "Sunting anak",
    "nameLabel": "Nama anak",
    "healthLabel": "Masalah kesihatan",
    "optional": "pilihan",
    "save": "Simpan",
    "addBtn": "Tambah anak",
    "cancel": "Batal",
    "underOne": "Bawah 1 tahun",
    "years": "tahun",
    "checkDangerFor": "Semak bahaya untuk"
  }
};
