// English source bag for runtime UI translation of languages not statically bundled.
import type { UIStrings } from "./uiStrings";
import type { ProfileStrings } from "./profileStrings";

export const EN_UI_SOURCE: UIStrings = {
  "isMyChildInDanger": "Is my child in danger?",
  "myChildIsSick": "My child is sick",
  "sendAPhoto": "Send a photo",
  "helpWithoutInternet": "Help without internet",
  "worldMap": "World map",
  "myChildren": "My children",
  "about": "About",
  "emergencyNow": "EMERGENCY — help me now",
  "emergencyNumbers": "Emergency numbers",
  "tapToCall": "Tap a number to call",
  "worksOffline": "Works without internet",
  "callNow": "Call now",
  "heroTitle": "Keeping children safe from weather danger",
  "heroSub": "Floods, heat, storms, bad air — see if your child is safe and what to do. In your language. Free.",
  "cardRiskDesc": "See the danger near your home, for your child's age.",
  "cardHealthDesc": "Tell us what is wrong — speak or type in your language.",
  "cardPhotoDesc": "Take a photo of a rash, wound, flood or smoke. We look at it and tell you what to do.",
  "cardMapDesc": "See where danger for children is high around the world.",
  "open": "Open",
  "statChildren": "Children exposed to 3+ climate hazards",
  "statStudents": "Students with schooling disrupted in 2024",
  "statDisplaced": "Child displacements per day from climate",
  "statCountries": "Countries · 55 languages supported",
  "whyTitle": "Why we built this",
  "storiesTitle": "Real emergency situations",
  "storiesSub": "How families use ClimaGuard when it matters most",
  "countriesTitle": "Built for the world's most vulnerable children",
  "countriesSub": "Covering all UNICEF high-risk countries with local language support",
  "moreCountries": "+51 more countries",
  "ctaTitle": "Start protecting your child now",
  "ctaSub": "Choose your country and your child's age — get an answer and a plan in your language.",
  "chipNoAccount": "No account needed",
  "chipFree": "100% free",
  "chipLanguages": "55 languages",
  "notMedical": "Not a substitute for medical advice.",
  "language": "Language",
  "country": "Country",
  "childAge": "Child's age",
  "checkNow": "Check now",
  "checking": "Checking…",
  "tapMicSpeak": "Tap the microphone and speak in your language",
  "recording": "Listening… tap the microphone again when you finish",
  "listen": "Listen",
  "stop": "Stop",
  "typeOrSpeak": "Type here, or tap the microphone and speak",
  "send": "Send",
  "riskLow": "Your child is safe right now.",
  "riskMedium": "Be careful. Watch your child.",
  "riskHigh": "Danger. Keep your child inside and safe.",
  "riskCritical": "VERY DANGEROUS! Get help now.",
  "heatLabel": "Heat",
  "heatDanger": "It is too hot for children. Keep them cool, give water.",
  "heatOk": "The heat is okay for children.",
  "sunLabel": "Sun",
  "sunDanger": "The sun is very strong. Keep children in the shade.",
  "sunOk": "The sun is okay.",
  "airLabel": "Air",
  "airDanger": "The air is bad. Keep children inside.",
  "airOk": "The air is okay.",
  "rainLabel": "Rain",
  "rainDanger": "Heavy rain. Water may rise. Go to a high, safe place.",
  "rainOk": "The rain is okay."
};

export const EN_PROFILE_SOURCE: ProfileStrings = {
  "backHome": "Back",
  "intro": "Set up each child once — age, place, and language. The active child personalizes every tool. Saved on your device and synced across devices.",
  "syncing": "syncing…",
  "addChild": "Add a child",
  "noChildren": "No children added yet — the app still works. Add a child to make every tool personal.",
  "active": "Active",
  "setActive": "Set active",
  "edit": "Edit",
  "remove": "Remove",
  "editTitle": "Edit child",
  "nameLabel": "Child's name",
  "healthLabel": "Health problems",
  "optional": "optional",
  "save": "Save",
  "addBtn": "Add child",
  "cancel": "Cancel",
  "underOne": "Under 1 year",
  "years": "years",
  "checkDangerFor": "Check danger for"
};
