// Localized UI chrome strings — the buttons, labels and plain-language
// sentences a parent must be able to read BEFORE any AI call happens.
// The AI already answers in 55 languages; this file makes the path to the AI
// (navigation, mic prompt, emergency button, risk sentences) readable too.
//
// Written for low-literacy readers: short sentences, everyday words, no
// technical terms ("Calculate", "Vision", "AQI", "offline" are banned here).
// Languages cover the dominant languages of the 66 UNICEF high-risk countries;
// anything else falls back to English.

export type UIStrings = {
  // Plain-language navigation (per parent feedback: name the need, not the tool)
  isMyChildInDanger: string; // → /dashboard  (was "Calculate Risk")
  myChildIsSick: string;     // → /health     (was "Health Advisor")
  sendAPhoto: string;        // → /vision     (was "Vision Analyzer")
  helpWithoutInternet: string; // → /offline-guide (was "Offline Guide")
  worldMap: string;
  myChildren: string;
  // Emergency
  emergencyNow: string;      // the one big button
  emergencyNumbers: string;
  tapToCall: string;
  worksOffline: string;
  callNow: string;
  // Home hero
  heroTitle: string;
  heroSub: string;
  // Form labels
  language: string;
  country: string;
  childAge: string;
  checkNow: string;
  checking: string;
  // Voice + read-aloud
  tapMicSpeak: string;
  recording: string;
  listen: string;
  stop: string;
  typeOrSpeak: string;
  send: string;
  // One-sentence risk meaning (color badge + this sentence, numbers optional)
  riskLow: string;
  riskMedium: string;
  riskHigh: string;
  riskCritical: string;
  // Plain weather sentences
  heatLabel: string; heatDanger: string; heatOk: string;
  sunLabel: string;  sunDanger: string;  sunOk: string;
  airLabel: string;  airDanger: string;  airOk: string;
  rainLabel: string; rainDanger: string; rainOk: string;
};

export const UI_STRINGS: Record<string, UIStrings> = {
  en: {
    isMyChildInDanger: "Is my child in danger?",
    myChildIsSick: "My child is sick",
    sendAPhoto: "Send a photo",
    helpWithoutInternet: "Help without internet",
    worldMap: "World map",
    myChildren: "My children",
    emergencyNow: "EMERGENCY — help me now",
    emergencyNumbers: "Emergency numbers",
    tapToCall: "Tap a number to call",
    worksOffline: "Works without internet",
    callNow: "Call now",
    heroTitle: "Keeping children safe from weather danger",
    heroSub: "Floods, heat, storms, bad air — see if your child is safe and what to do. In your language. Free.",
    language: "Language",
    country: "Country",
    childAge: "Child's age",
    checkNow: "Check now",
    checking: "Checking…",
    tapMicSpeak: "Tap the microphone and speak in your language",
    recording: "Listening… tap the microphone again when you finish",
    listen: "Listen",
    stop: "Stop",
    typeOrSpeak: "Type here, or tap the microphone and speak",
    send: "Send",
    riskLow: "Your child is safe right now.",
    riskMedium: "Be careful. Watch your child.",
    riskHigh: "Danger. Keep your child inside and safe.",
    riskCritical: "VERY DANGEROUS! Get help now.",
    heatLabel: "Heat", heatDanger: "It is too hot for children. Keep them cool, give water.", heatOk: "The heat is okay for children.",
    sunLabel: "Sun", sunDanger: "The sun is very strong. Keep children in the shade.", sunOk: "The sun is okay.",
    airLabel: "Air", airDanger: "The air is bad. Keep children inside.", airOk: "The air is okay.",
    rainLabel: "Rain", rainDanger: "Heavy rain. Water may rise. Go to a high, safe place.", rainOk: "The rain is okay.",
  },
  bn: {
    isMyChildInDanger: "আমার শিশু কি বিপদে আছে?",
    myChildIsSick: "আমার শিশু অসুস্থ",
    sendAPhoto: "ছবি পাঠান",
    helpWithoutInternet: "ইন্টারনেট ছাড়া সাহায্য",
    worldMap: "বিশ্ব মানচিত্র",
    myChildren: "আমার শিশুরা",
    emergencyNow: "জরুরি — এখনই সাহায্য চাই",
    emergencyNumbers: "জরুরি ফোন নম্বর",
    tapToCall: "নম্বরে চাপ দিলে ফোন যাবে",
    worksOffline: "ইন্টারনেট ছাড়াও কাজ করে",
    callNow: "এখনই ফোন করুন",
    heroTitle: "আবহাওয়ার বিপদ থেকে শিশুদের নিরাপদ রাখুন",
    heroSub: "বন্যা, গরম, ঝড়, খারাপ বাতাস — আপনার শিশু নিরাপদ কি না দেখুন, কী করবেন জানুন। আপনার ভাষায়। বিনামূল্যে।",
    language: "ভাষা",
    country: "দেশ",
    childAge: "শিশুর বয়স",
    checkNow: "এখনই দেখুন",
    checking: "দেখা হচ্ছে…",
    tapMicSpeak: "মাইকে চাপ দিন, নিজের ভাষায় বলুন",
    recording: "শোনা হচ্ছে… বলা শেষ হলে আবার মাইকে চাপ দিন",
    listen: "শুনুন",
    stop: "থামুন",
    typeOrSpeak: "এখানে লিখুন, অথবা মাইকে চাপ দিয়ে বলুন",
    send: "পাঠান",
    riskLow: "আপনার শিশু এখন নিরাপদ।",
    riskMedium: "সাবধান থাকুন। শিশুর দিকে খেয়াল রাখুন।",
    riskHigh: "বিপদ। শিশুকে ঘরের ভিতরে নিরাপদে রাখুন।",
    riskCritical: "খুব বিপজ্জনক! এখনই সাহায্য নিন।",
    heatLabel: "গরম", heatDanger: "শিশুদের জন্য খুব বেশি গরম। ঠান্ডা রাখুন, পানি দিন।", heatOk: "গরম এখন শিশুদের জন্য সহনীয়।",
    sunLabel: "রোদ", sunDanger: "রোদ খুব কড়া। শিশুদের ছায়ায় রাখুন।", sunOk: "রোদ এখন ঠিক আছে।",
    airLabel: "বাতাস", airDanger: "বাতাস খারাপ। শিশুদের ঘরের ভিতরে রাখুন।", airOk: "বাতাস এখন ঠিক আছে।",
    rainLabel: "বৃষ্টি", rainDanger: "ভারী বৃষ্টি। পানি বাড়তে পারে। উঁচু নিরাপদ জায়গায় যান।", rainOk: "বৃষ্টি এখন ঠিক আছে।",
  },
  hi: {
    isMyChildInDanger: "क्या मेरा बच्चा खतरे में है?",
    myChildIsSick: "मेरा बच्चा बीमार है",
    sendAPhoto: "फोटो भेजें",
    helpWithoutInternet: "बिना इंटरनेट मदद",
    worldMap: "विश्व नक्शा",
    myChildren: "मेरे बच्चे",
    emergencyNow: "आपातकाल — अभी मदद चाहिए",
    emergencyNumbers: "आपातकालीन फोन नंबर",
    tapToCall: "नंबर दबाते ही कॉल लगेगा",
    worksOffline: "बिना इंटरनेट भी चलता है",
    callNow: "अभी कॉल करें",
    heroTitle: "मौसम के खतरों से बच्चों को सुरक्षित रखें",
    heroSub: "बाढ़, गर्मी, तूफान, खराब हवा — देखें कि आपका बच्चा सुरक्षित है या नहीं, और क्या करें। आपकी भाषा में। मुफ्त।",
    language: "भाषा",
    country: "देश",
    childAge: "बच्चे की उम्र",
    checkNow: "अभी जांचें",
    checking: "जांच हो रही है…",
    tapMicSpeak: "माइक दबाएँ, अपनी भाषा में बोलें",
    recording: "सुन रहे हैं… बोलना खत्म होने पर फिर माइक दबाएँ",
    listen: "सुनें",
    stop: "रोकें",
    typeOrSpeak: "यहाँ लिखें, या माइक दबाकर बोलें",
    send: "भेजें",
    riskLow: "आपका बच्चा अभी सुरक्षित है।",
    riskMedium: "सावधान रहें। बच्चे पर नज़र रखें।",
    riskHigh: "खतरा। बच्चे को घर के अंदर सुरक्षित रखें।",
    riskCritical: "बहुत खतरनाक! अभी मदद लें।",
    heatLabel: "गर्मी", heatDanger: "बच्चों के लिए बहुत गर्मी है। ठंडा रखें, पानी दें।", heatOk: "गर्मी अभी ठीक है।",
    sunLabel: "धूप", sunDanger: "धूप बहुत तेज़ है। बच्चों को छाया में रखें।", sunOk: "धूप अभी ठीक है।",
    airLabel: "हवा", airDanger: "हवा खराब है। बच्चों को घर के अंदर रखें।", airOk: "हवा अभी ठीक है।",
    rainLabel: "बारिश", rainDanger: "भारी बारिश। पानी बढ़ सकता है। ऊँची सुरक्षित जगह जाएँ।", rainOk: "बारिश अभी ठीक है।",
  },
  ur: {
    isMyChildInDanger: "کیا میرا بچہ خطرے میں ہے؟",
    myChildIsSick: "میرا بچہ بیمار ہے",
    sendAPhoto: "تصویر بھیجیں",
    helpWithoutInternet: "انٹرنیٹ کے بغیر مدد",
    worldMap: "دنیا کا نقشہ",
    myChildren: "میرے بچے",
    emergencyNow: "ایمرجنسی — ابھی مدد چاہیے",
    emergencyNumbers: "ایمرجنسی فون نمبر",
    tapToCall: "نمبر دبائیں تو کال لگے گی",
    worksOffline: "انٹرنیٹ کے بغیر بھی چلتا ہے",
    callNow: "ابھی کال کریں",
    heroTitle: "موسم کے خطروں سے بچوں کو محفوظ رکھیں",
    heroSub: "سیلاب، گرمی، طوفان، خراب ہوا — دیکھیں کہ آپ کا بچہ محفوظ ہے یا نہیں، اور کیا کریں۔ آپ کی زبان میں۔ مفت۔",
    language: "زبان",
    country: "ملک",
    childAge: "بچے کی عمر",
    checkNow: "ابھی دیکھیں",
    checking: "دیکھا جا رہا ہے…",
    tapMicSpeak: "مائیک دبائیں، اپنی زبان میں بولیں",
    recording: "سن رہے ہیں… بات ختم ہو تو دوبارہ مائیک دبائیں",
    listen: "سنیں",
    stop: "روکیں",
    typeOrSpeak: "یہاں لکھیں، یا مائیک دبا کر بولیں",
    send: "بھیجیں",
    riskLow: "آپ کا بچہ ابھی محفوظ ہے۔",
    riskMedium: "محتاط رہیں۔ بچے کا خیال رکھیں۔",
    riskHigh: "خطرہ۔ بچے کو گھر کے اندر محفوظ رکھیں۔",
    riskCritical: "بہت خطرناک! ابھی مدد لیں۔",
    heatLabel: "گرمی", heatDanger: "بچوں کے لیے بہت گرمی ہے۔ ٹھنڈا رکھیں، پانی دیں۔", heatOk: "گرمی ابھی ٹھیک ہے۔",
    sunLabel: "دھوپ", sunDanger: "دھوپ بہت تیز ہے۔ بچوں کو سائے میں رکھیں۔", sunOk: "دھوپ ابھی ٹھیک ہے۔",
    airLabel: "ہوا", airDanger: "ہوا خراب ہے۔ بچوں کو گھر کے اندر رکھیں۔", airOk: "ہوا ابھی ٹھیک ہے۔",
    rainLabel: "بارش", rainDanger: "تیز بارش۔ پانی بڑھ سکتا ہے۔ اونچی محفوظ جگہ جائیں۔", rainOk: "بارش ابھی ٹھیک ہے۔",
  },
  ar: {
    isMyChildInDanger: "هل طفلي في خطر؟",
    myChildIsSick: "طفلي مريض",
    sendAPhoto: "أرسل صورة",
    helpWithoutInternet: "مساعدة بدون إنترنت",
    worldMap: "خريطة العالم",
    myChildren: "أطفالي",
    emergencyNow: "طوارئ — أحتاج مساعدة الآن",
    emergencyNumbers: "أرقام الطوارئ",
    tapToCall: "اضغط على الرقم للاتصال",
    worksOffline: "يعمل بدون إنترنت",
    callNow: "اتصل الآن",
    heroTitle: "حماية الأطفال من أخطار الطقس",
    heroSub: "فيضانات، حر شديد، عواصف، هواء ملوث — اعرف إن كان طفلك بأمان وماذا تفعل. بلغتك. مجانًا.",
    language: "اللغة",
    country: "الدولة",
    childAge: "عمر الطفل",
    checkNow: "افحص الآن",
    checking: "جارٍ الفحص…",
    tapMicSpeak: "اضغط على الميكروفون وتكلم بلغتك",
    recording: "نستمع… اضغط على الميكروفون مرة أخرى عند الانتهاء",
    listen: "استمع",
    stop: "أوقف",
    typeOrSpeak: "اكتب هنا، أو اضغط على الميكروفون وتكلم",
    send: "أرسل",
    riskLow: "طفلك بأمان الآن.",
    riskMedium: "كن حذرًا. راقب طفلك.",
    riskHigh: "خطر. أبقِ طفلك داخل البيت بأمان.",
    riskCritical: "خطر شديد! اطلب المساعدة الآن.",
    heatLabel: "الحر", heatDanger: "الجو حار جدًا على الأطفال. برّدهم وأعطهم ماء.", heatOk: "الحرارة مقبولة الآن.",
    sunLabel: "الشمس", sunDanger: "الشمس قوية جدًا. أبقِ الأطفال في الظل.", sunOk: "الشمس مقبولة الآن.",
    airLabel: "الهواء", airDanger: "الهواء ملوث. أبقِ الأطفال داخل البيت.", airOk: "الهواء جيد الآن.",
    rainLabel: "المطر", rainDanger: "مطر غزير. قد يرتفع الماء. اذهب إلى مكان مرتفع وآمن.", rainOk: "المطر مقبول الآن.",
  },
  fr: {
    isMyChildInDanger: "Mon enfant est-il en danger ?",
    myChildIsSick: "Mon enfant est malade",
    sendAPhoto: "Envoyer une photo",
    helpWithoutInternet: "Aide sans internet",
    worldMap: "Carte du monde",
    myChildren: "Mes enfants",
    emergencyNow: "URGENCE — aidez-moi maintenant",
    emergencyNumbers: "Numéros d'urgence",
    tapToCall: "Touchez un numéro pour appeler",
    worksOffline: "Fonctionne sans internet",
    callNow: "Appeler maintenant",
    heroTitle: "Protéger les enfants des dangers du climat",
    heroSub: "Inondations, chaleur, tempêtes, air pollué — vérifiez si votre enfant est en sécurité et que faire. Dans votre langue. Gratuit.",
    language: "Langue",
    country: "Pays",
    childAge: "Âge de l'enfant",
    checkNow: "Vérifier maintenant",
    checking: "Vérification…",
    tapMicSpeak: "Touchez le micro et parlez dans votre langue",
    recording: "On vous écoute… touchez encore le micro quand vous avez fini",
    listen: "Écouter",
    stop: "Arrêter",
    typeOrSpeak: "Écrivez ici, ou touchez le micro et parlez",
    send: "Envoyer",
    riskLow: "Votre enfant est en sécurité pour le moment.",
    riskMedium: "Soyez prudent. Surveillez votre enfant.",
    riskHigh: "Danger. Gardez votre enfant à l'intérieur, en sécurité.",
    riskCritical: "TRÈS DANGEREUX ! Cherchez de l'aide maintenant.",
    heatLabel: "Chaleur", heatDanger: "Il fait trop chaud pour les enfants. Rafraîchissez-les, donnez de l'eau.", heatOk: "La chaleur est supportable.",
    sunLabel: "Soleil", sunDanger: "Le soleil est très fort. Gardez les enfants à l'ombre.", sunOk: "Le soleil ne pose pas de problème.",
    airLabel: "Air", airDanger: "L'air est mauvais. Gardez les enfants à l'intérieur.", airOk: "L'air est bon.",
    rainLabel: "Pluie", rainDanger: "Pluie forte. L'eau peut monter. Allez vers un lieu haut et sûr.", rainOk: "La pluie ne pose pas de problème.",
  },
  es: {
    isMyChildInDanger: "¿Mi hijo está en peligro?",
    myChildIsSick: "Mi hijo está enfermo",
    sendAPhoto: "Enviar una foto",
    helpWithoutInternet: "Ayuda sin internet",
    worldMap: "Mapa mundial",
    myChildren: "Mis hijos",
    emergencyNow: "EMERGENCIA — ayuda ahora",
    emergencyNumbers: "Números de emergencia",
    tapToCall: "Toque un número para llamar",
    worksOffline: "Funciona sin internet",
    callNow: "Llamar ahora",
    heroTitle: "Proteger a los niños de los peligros del clima",
    heroSub: "Inundaciones, calor, tormentas, aire contaminado — vea si su hijo está seguro y qué hacer. En su idioma. Gratis.",
    language: "Idioma",
    country: "País",
    childAge: "Edad del niño",
    checkNow: "Comprobar ahora",
    checking: "Comprobando…",
    tapMicSpeak: "Toque el micrófono y hable en su idioma",
    recording: "Escuchando… toque el micrófono otra vez al terminar",
    listen: "Escuchar",
    stop: "Detener",
    typeOrSpeak: "Escriba aquí, o toque el micrófono y hable",
    send: "Enviar",
    riskLow: "Su hijo está seguro ahora.",
    riskMedium: "Tenga cuidado. Vigile a su hijo.",
    riskHigh: "Peligro. Mantenga a su hijo dentro y seguro.",
    riskCritical: "¡MUY PELIGROSO! Busque ayuda ahora.",
    heatLabel: "Calor", heatDanger: "Hace demasiado calor para los niños. Refrésquelos y deles agua.", heatOk: "El calor está bien ahora.",
    sunLabel: "Sol", sunDanger: "El sol está muy fuerte. Mantenga a los niños a la sombra.", sunOk: "El sol está bien ahora.",
    airLabel: "Aire", airDanger: "El aire está malo. Mantenga a los niños dentro.", airOk: "El aire está bien ahora.",
    rainLabel: "Lluvia", rainDanger: "Lluvia fuerte. El agua puede subir. Vaya a un lugar alto y seguro.", rainOk: "La lluvia está bien ahora.",
  },
  pt: {
    isMyChildInDanger: "O meu filho está em perigo?",
    myChildIsSick: "O meu filho está doente",
    sendAPhoto: "Enviar uma foto",
    helpWithoutInternet: "Ajuda sem internet",
    worldMap: "Mapa do mundo",
    myChildren: "Os meus filhos",
    emergencyNow: "EMERGÊNCIA — preciso de ajuda agora",
    emergencyNumbers: "Números de emergência",
    tapToCall: "Toque num número para ligar",
    worksOffline: "Funciona sem internet",
    callNow: "Ligar agora",
    heroTitle: "Proteger as crianças dos perigos do clima",
    heroSub: "Cheias, calor, tempestades, ar poluído — veja se o seu filho está seguro e o que fazer. Na sua língua. Grátis.",
    language: "Língua",
    country: "País",
    childAge: "Idade da criança",
    checkNow: "Verificar agora",
    checking: "A verificar…",
    tapMicSpeak: "Toque no microfone e fale na sua língua",
    recording: "A ouvir… toque no microfone outra vez quando terminar",
    listen: "Ouvir",
    stop: "Parar",
    typeOrSpeak: "Escreva aqui, ou toque no microfone e fale",
    send: "Enviar",
    riskLow: "O seu filho está seguro agora.",
    riskMedium: "Tenha cuidado. Vigie o seu filho.",
    riskHigh: "Perigo. Mantenha o seu filho dentro de casa, em segurança.",
    riskCritical: "MUITO PERIGOSO! Procure ajuda agora.",
    heatLabel: "Calor", heatDanger: "Está calor demais para as crianças. Refresque-as e dê água.", heatOk: "O calor está bem agora.",
    sunLabel: "Sol", sunDanger: "O sol está muito forte. Mantenha as crianças à sombra.", sunOk: "O sol está bem agora.",
    airLabel: "Ar", airDanger: "O ar está mau. Mantenha as crianças dentro de casa.", airOk: "O ar está bom agora.",
    rainLabel: "Chuva", rainDanger: "Chuva forte. A água pode subir. Vá para um lugar alto e seguro.", rainOk: "A chuva está bem agora.",
  },
  sw: {
    isMyChildInDanger: "Je, mtoto wangu yuko hatarini?",
    myChildIsSick: "Mtoto wangu ni mgonjwa",
    sendAPhoto: "Tuma picha",
    helpWithoutInternet: "Msaada bila intaneti",
    worldMap: "Ramani ya dunia",
    myChildren: "Watoto wangu",
    emergencyNow: "DHARURA — nisaidie sasa",
    emergencyNumbers: "Namba za dharura",
    tapToCall: "Gusa namba ili kupiga simu",
    worksOffline: "Inafanya kazi bila intaneti",
    callNow: "Piga simu sasa",
    heroTitle: "Kulinda watoto dhidi ya hatari za hali ya hewa",
    heroSub: "Mafuriko, joto kali, dhoruba, hewa chafu — angalia kama mtoto wako yuko salama na cha kufanya. Kwa lugha yako. Bure.",
    language: "Lugha",
    country: "Nchi",
    childAge: "Umri wa mtoto",
    checkNow: "Angalia sasa",
    checking: "Inaangalia…",
    tapMicSpeak: "Gusa kipaza sauti, ongea kwa lugha yako",
    recording: "Tunasikiliza… gusa kipaza sauti tena ukimaliza",
    listen: "Sikiliza",
    stop: "Simamisha",
    typeOrSpeak: "Andika hapa, au gusa kipaza sauti uongee",
    send: "Tuma",
    riskLow: "Mtoto wako yuko salama sasa.",
    riskMedium: "Kuwa makini. Mwangalie mtoto wako.",
    riskHigh: "Hatari. Mweke mtoto ndani, salama.",
    riskCritical: "HATARI KUBWA! Tafuta msaada sasa.",
    heatLabel: "Joto", heatDanger: "Kuna joto kali sana kwa watoto. Wapoze, wape maji.", heatOk: "Joto liko sawa sasa.",
    sunLabel: "Jua", sunDanger: "Jua ni kali sana. Waweke watoto kivulini.", sunOk: "Jua liko sawa sasa.",
    airLabel: "Hewa", airDanger: "Hewa ni chafu. Waweke watoto ndani.", airOk: "Hewa iko safi sasa.",
    rainLabel: "Mvua", rainDanger: "Mvua kubwa. Maji yanaweza kupanda. Nenda mahali pa juu na salama.", rainOk: "Mvua iko sawa sasa.",
  },
  ha: {
    isMyChildInDanger: "Shin ɗana yana cikin haɗari?",
    myChildIsSick: "Ɗana yana rashin lafiya",
    sendAPhoto: "Aika hoto",
    helpWithoutInternet: "Taimako ba tare da intanet ba",
    worldMap: "Taswirar duniya",
    myChildren: "Yarana",
    emergencyNow: "GAGGAWA — a taimake ni yanzu",
    emergencyNumbers: "Lambobin gaggawa",
    tapToCall: "Danna lamba don kira",
    worksOffline: "Yana aiki ba tare da intanet ba",
    callNow: "Kira yanzu",
    heroTitle: "Kare yara daga haɗarin yanayi",
    heroSub: "Ambaliya, zafi, hadari, gurɓataccen iska — duba ko yaronka yana lafiya da abin da za ka yi. Da yarenka. Kyauta.",
    language: "Harshe",
    country: "Ƙasa",
    childAge: "Shekarun yaro",
    checkNow: "Duba yanzu",
    checking: "Ana dubawa…",
    tapMicSpeak: "Danna makirufo, yi magana da yarenka",
    recording: "Muna saurare… danna makirufo kuma idan ka gama",
    listen: "Saurara",
    stop: "Tsaya",
    typeOrSpeak: "Rubuta a nan, ko danna makirufo ka yi magana",
    send: "Aika",
    riskLow: "Yaronka yana lafiya yanzu.",
    riskMedium: "Yi hankali. Kula da yaronka.",
    riskHigh: "Haɗari. Ajiye yaronka a cikin gida lafiya.",
    riskCritical: "HAƊARI SOSAI! Nemi taimako yanzu.",
    heatLabel: "Zafi", heatDanger: "Zafi ya yi yawa ga yara. Sanyaya su, ba su ruwa.", heatOk: "Zafi ba matsala yanzu.",
    sunLabel: "Rana", sunDanger: "Rana tana da ƙarfi sosai. Ajiye yara a inuwa.", sunOk: "Rana ba matsala yanzu.",
    airLabel: "Iska", airDanger: "Iska ba ta da kyau. Ajiye yara a cikin gida.", airOk: "Iska tana da kyau yanzu.",
    rainLabel: "Ruwan sama", rainDanger: "Ruwan sama mai ƙarfi. Ruwa na iya hauhawa. Je wuri mai tsayi da aminci.", rainOk: "Ruwan sama ba matsala yanzu.",
  },
  am: {
    isMyChildInDanger: "ልጄ አደጋ ላይ ነው?",
    myChildIsSick: "ልጄ ታሟል",
    sendAPhoto: "ፎቶ ላክ",
    helpWithoutInternet: "ያለ ኢንተርኔት እርዳታ",
    worldMap: "የዓለም ካርታ",
    myChildren: "ልጆቼ",
    emergencyNow: "አደጋ — አሁን እርዱኝ",
    emergencyNumbers: "የአደጋ ጊዜ ስልኮች",
    tapToCall: "ለመደወል ቁጥሩን ይንኩ",
    worksOffline: "ያለ ኢንተርኔት ይሰራል",
    callNow: "አሁን ይደውሉ",
    heroTitle: "ልጆችን ከአየር ንብረት አደጋ መጠበቅ",
    heroSub: "ጎርፍ፣ ሙቀት፣ አውሎ ነፋስ፣ መጥፎ አየር — ልጅዎ ደህና መሆኑን እና ምን ማድረግ እንዳለብዎ ይመልከቱ። በቋንቋዎ። በነጻ።",
    language: "ቋንቋ",
    country: "አገር",
    childAge: "የልጅ ዕድሜ",
    checkNow: "አሁን ይመልከቱ",
    checking: "በመፈተሽ ላይ…",
    tapMicSpeak: "ማይክሩን ይንኩ፣ በቋንቋዎ ይናገሩ",
    recording: "እያዳመጥን ነው… ሲጨርሱ ማይክሩን እንደገና ይንኩ",
    listen: "ያዳምጡ",
    stop: "አቁም",
    typeOrSpeak: "እዚህ ይጻፉ፣ ወይም ማይክሩን ነክተው ይናገሩ",
    send: "ላክ",
    riskLow: "ልጅዎ አሁን ደህና ነው።",
    riskMedium: "ይጠንቀቁ። ልጅዎን ይከታተሉ።",
    riskHigh: "አደጋ። ልጅዎን በቤት ውስጥ ደህንነቱ በተጠበቀ ሁኔታ ያቆዩ።",
    riskCritical: "በጣም አደገኛ! አሁን እርዳታ ይፈልጉ።",
    heatLabel: "ሙቀት", heatDanger: "ለልጆች በጣም ሞቃት ነው። ያቀዘቅዙ፣ ውሃ ይስጡ።", heatOk: "ሙቀቱ አሁን ችግር የለውም።",
    sunLabel: "ፀሐይ", sunDanger: "ፀሐይ በጣም ኃይለኛ ነው። ልጆችን በጥላ ውስጥ ያቆዩ።", sunOk: "ፀሐይ አሁን ችግር የለውም።",
    airLabel: "አየር", airDanger: "አየሩ መጥፎ ነው። ልጆችን በቤት ውስጥ ያቆዩ።", airOk: "አየሩ አሁን ጥሩ ነው።",
    rainLabel: "ዝናብ", rainDanger: "ኃይለኛ ዝናብ። ውሃ ሊጨምር ይችላል። ወደ ከፍ ያለ ደህና ቦታ ይሂዱ።", rainOk: "ዝናቡ አሁን ችግር የለውም።",
  },
  so: {
    isMyChildInDanger: "Ilmahaygu ma khatar buu ku jiraa?",
    myChildIsSick: "Ilmahaygu wuu xanuunsanayaa",
    sendAPhoto: "Sawir dir",
    helpWithoutInternet: "Caawimaad internet la'aan",
    worldMap: "Khariidadda adduunka",
    myChildren: "Carruurtayda",
    emergencyNow: "DEG DEG — hadda i caawiya",
    emergencyNumbers: "Lambarrada gurmadka",
    tapToCall: "Taabo lambarka si aad u wacdo",
    worksOffline: "Wuxuu shaqeeyaa internet la'aan",
    callNow: "Hadda wac",
    heroTitle: "Ka ilaalinta carruurta khatarta cimilada",
    heroSub: "Daadad, kulayl, duufaanno, hawo xun — eeg in ilmahaagu nabad yahay iyo waxa la sameeyo. Luqaddaada. Bilaash.",
    language: "Luqadda",
    country: "Dalka",
    childAge: "Da'da ilmaha",
    checkNow: "Hadda hubi",
    checking: "Waa la hubinayaa…",
    tapMicSpeak: "Taabo makarafoonka, kuna hadal luqaddaada",
    recording: "Waan dhegeysanaynaa… mar kale taabo makarafoonka markaad dhammayso",
    listen: "Dhegayso",
    stop: "Jooji",
    typeOrSpeak: "Halkan wax ku qor, ama taabo makarafoonka oo hadal",
    send: "Dir",
    riskLow: "Ilmahaagu hadda waa nabad.",
    riskMedium: "Ka taxaddar. Ilaali ilmahaaga.",
    riskHigh: "Khatar. Ilmahaaga gudaha ku hay si nabad ah.",
    riskCritical: "AAD U KHATAR AH! Hadda caawimaad raadso.",
    heatLabel: "Kulayl", heatDanger: "Aad bay ugu kulushahay carruurta. Qabooji, biyo sii.", heatOk: "Kulaylku hadda waa caadi.",
    sunLabel: "Qorrax", sunDanger: "Qorraxdu aad bay u daran tahay. Carruurta hooska ku hay.", sunOk: "Qorraxdu hadda waa caadi.",
    airLabel: "Hawo", airDanger: "Hawadu waa xun tahay. Carruurta gudaha ku hay.", airOk: "Hawadu hadda waa fiican tahay.",
    rainLabel: "Roob", rainDanger: "Roob weyn. Biyuhu way kori karaan. Aad meel sare oo nabad ah.", rainOk: "Roobku hadda waa caadi.",
  },
  fil: {
    isMyChildInDanger: "Nasa panganib ba ang anak ko?",
    myChildIsSick: "May sakit ang anak ko",
    sendAPhoto: "Magpadala ng litrato",
    helpWithoutInternet: "Tulong kahit walang internet",
    worldMap: "Mapa ng mundo",
    myChildren: "Mga anak ko",
    emergencyNow: "EMERGENCY — tulungan ninyo ako ngayon",
    emergencyNumbers: "Mga emergency na numero",
    tapToCall: "Pindutin ang numero para tumawag",
    worksOffline: "Gumagana kahit walang internet",
    callNow: "Tumawag ngayon",
    heroTitle: "Pagprotekta sa mga bata mula sa panganib ng panahon",
    heroSub: "Baha, init, bagyo, maruming hangin — tingnan kung ligtas ang inyong anak at ano ang gagawin. Sa inyong wika. Libre.",
    language: "Wika",
    country: "Bansa",
    childAge: "Edad ng bata",
    checkNow: "Tingnan ngayon",
    checking: "Tinitingnan…",
    tapMicSpeak: "Pindutin ang mikropono at magsalita sa inyong wika",
    recording: "Nakikinig… pindutin ulit ang mikropono kapag tapos na",
    listen: "Pakinggan",
    stop: "Ihinto",
    typeOrSpeak: "Magsulat dito, o pindutin ang mikropono at magsalita",
    send: "Ipadala",
    riskLow: "Ligtas ang inyong anak ngayon.",
    riskMedium: "Mag-ingat. Bantayan ang inyong anak.",
    riskHigh: "Panganib. Panatilihin ang bata sa loob ng bahay, ligtas.",
    riskCritical: "NAPAKADELIKADO! Humingi ng tulong ngayon.",
    heatLabel: "Init", heatDanger: "Sobrang init para sa mga bata. Palamigin sila, painumin ng tubig.", heatOk: "Ayos lang ang init ngayon.",
    sunLabel: "Araw", sunDanger: "Napakatindi ng araw. Ilagay ang mga bata sa lilim.", sunOk: "Ayos lang ang araw ngayon.",
    airLabel: "Hangin", airDanger: "Marumi ang hangin. Panatilihin ang mga bata sa loob.", airOk: "Malinis ang hangin ngayon.",
    rainLabel: "Ulan", rainDanger: "Malakas na ulan. Maaaring tumaas ang tubig. Pumunta sa mataas at ligtas na lugar.", rainOk: "Ayos lang ang ulan ngayon.",
  },
  id: {
    isMyChildInDanger: "Apakah anak saya dalam bahaya?",
    myChildIsSick: "Anak saya sakit",
    sendAPhoto: "Kirim foto",
    helpWithoutInternet: "Bantuan tanpa internet",
    worldMap: "Peta dunia",
    myChildren: "Anak-anak saya",
    emergencyNow: "DARURAT — tolong saya sekarang",
    emergencyNumbers: "Nomor darurat",
    tapToCall: "Ketuk nomor untuk menelepon",
    worksOffline: "Bekerja tanpa internet",
    callNow: "Telepon sekarang",
    heroTitle: "Melindungi anak dari bahaya cuaca",
    heroSub: "Banjir, panas, badai, udara kotor — lihat apakah anak Anda aman dan apa yang harus dilakukan. Dalam bahasa Anda. Gratis.",
    language: "Bahasa",
    country: "Negara",
    childAge: "Umur anak",
    checkNow: "Periksa sekarang",
    checking: "Memeriksa…",
    tapMicSpeak: "Ketuk mikrofon, bicaralah dalam bahasa Anda",
    recording: "Mendengarkan… ketuk mikrofon lagi jika sudah selesai",
    listen: "Dengarkan",
    stop: "Berhenti",
    typeOrSpeak: "Tulis di sini, atau ketuk mikrofon dan bicara",
    send: "Kirim",
    riskLow: "Anak Anda aman sekarang.",
    riskMedium: "Hati-hati. Awasi anak Anda.",
    riskHigh: "Bahaya. Jaga anak tetap di dalam rumah, aman.",
    riskCritical: "SANGAT BERBAHAYA! Cari bantuan sekarang.",
    heatLabel: "Panas", heatDanger: "Terlalu panas untuk anak-anak. Dinginkan mereka, beri air minum.", heatOk: "Panas tidak berbahaya sekarang.",
    sunLabel: "Matahari", sunDanger: "Matahari sangat terik. Jaga anak di tempat teduh.", sunOk: "Matahari tidak berbahaya sekarang.",
    airLabel: "Udara", airDanger: "Udara buruk. Jaga anak tetap di dalam rumah.", airOk: "Udara baik sekarang.",
    rainLabel: "Hujan", rainDanger: "Hujan deras. Air bisa naik. Pergilah ke tempat tinggi yang aman.", rainOk: "Hujan tidak berbahaya sekarang.",
  },
};

// Native (endonym) names so a parent can find their language even when the
// current UI language is unreadable to them — shown in the language picker.
export const NATIVE_LANGUAGE_NAMES: Record<string, string> = {
  bn: "বাংলা", hi: "हिन्दी", ur: "اردو", ar: "العربية", en: "English",
  fr: "Français", es: "Español", pt: "Português", sw: "Kiswahili",
  am: "አማርኛ", so: "Soomaali", ha: "Hausa", yo: "Yorùbá", ig: "Igbo",
  zu: "isiZulu", af: "Afrikaans", mg: "Malagasy", fil: "Filipino",
  id: "Bahasa Indonesia", ms: "Bahasa Melayu", vi: "Tiếng Việt", th: "ไทย",
  km: "ខ្មែរ", lo: "ລາວ", my: "မြန်မာ", tpi: "Tok Pisin", zh: "中文",
  ja: "日本語", ko: "한국어", ta: "தமிழ்", te: "తెలుగు", mr: "मराठी",
  gu: "ગુજરાતી", pa: "ਪੰਜਾਬੀ", kn: "ಕನ್ನಡ", ml: "മലയാളം", ne: "नेपाली",
  si: "සිංහල", fa: "فارسی", prs: "دری", ps: "پښتو", ku: "Kurdî",
  tk: "Türkmençe", tg: "Тоҷикӣ", ti: "ትግርኛ", rw: "Kinyarwanda",
  tr: "Türkçe", ru: "Русский", uk: "Українська", de: "Deutsch",
  it: "Italiano", nl: "Nederlands", pl: "Polski", el: "Ελληνικά", he: "עברית",
};

const RTL_LANGS = new Set(["ar", "ur", "fa", "prs", "ps", "he", "ku"]);

export const isRTL = (code: string): boolean => RTL_LANGS.has(code);

/** UI strings for a language code, falling back to English. */
export const getUIStrings = (code: string): UIStrings =>
  UI_STRINGS[code] ?? UI_STRINGS.en;
