// AUTO-GENERATED UI translations (Gemini 2.5 Flash), reviewed for key completeness.
// Extends the hand-written UI_STRINGS in uiStrings.ts.
import type { UIStrings } from "./uiStrings";

export const UI_STRINGS_AUTO: Record<string, UIStrings> = {
  "yo": {
    "isMyChildInDanger": "Ṣé ọmọ mi wà nínú ewu?",
    "myChildIsSick": "Ọmọ mi ṣàìsàn",
    "sendAPhoto": "Fi fọ́tò ránṣẹ́",
    "helpWithoutInternet": "Ìrànlọ́wọ́ láìsí Íntánẹ́ẹ̀tì",
    "worldMap": "Maapu ayé",
    "myChildren": "Àwọn ọmọ mi",
    "about": "Nípa",
    "emergencyNow": "PÀJÚBÀ — ràn mí lọ́wọ́ nísinsìnyí",
    "emergencyNumbers": "Àwọn nọ́ńbà pàjúbà",
    "tapToCall": "Fọwọ́ tẹ nọ́ńbà kan láti pè",
    "worksOffline": "Ṣiṣẹ́ láìsí Íntánẹ́ẹ̀tì",
    "callNow": "Pè nísinsìnyí",
    "tap": "TẸ",
    "heroTitle": "Dídáàbò bo àwọn ọmọ kúrò nínú ewu ojú ọjọ́",
    "heroSub": "Ìkún omi, ooru, ìjì, afẹ́fẹ́ búburú — wo bóyá ọmọ rẹ wà láìléwu àti ohun tí o lè ṣe. Nínú èdè rẹ. Ọfẹ́.",
    "cardRiskDesc": "Wo ewu tó wà nítòsí ilé rẹ, fún ọjọ́ orí ọmọ rẹ.",
    "cardHealthDesc": "Sọ ohun tó ṣẹlẹ̀ — sọ̀rọ̀ tàbí kọ̀wé ní èdè rẹ.",
    "cardPhotoDesc": "Yà fọ́tò egbò, ọgbẹ́, ìkún omi tàbí èéfín. A ó wò ó, a ó sì sọ ohun tí o lè ṣe.",
    "cardMapDesc": "Wo ibi tí ewu fún àwọn ọmọ ti pọ̀ ní àyíká ayé.",
    "open": "Ṣí",
    "statChildren": "Àwọn ọmọ tí ó dojú kọ 3+ ewu ojú ọjọ́",
    "statStudents": "Àwọn akẹ́kọ̀ọ́ tí ẹ̀kọ́ wọn dáwọ́ dúró ní 2024",
    "statDisplaced": "Ìṣíìpò àwọn ọmọ lójoojúmọ́ nítorí ojú ọjọ́",
    "statCountries": "Àwọn Orílẹ̀-èdè · 55 èdè ni a ṣe àtìlẹ́yìn fún",
    "whyTitle": "Ìdí tí a fi kọ́ èyí",
    "storiesTitle": "Àwọn ipò pàjúbà gidi",
    "storiesSub": "Bí àwọn ìdílé ṣe ń lo ClimaGuard nígbà tó ṣe pàtàkì jù",
    "countriesTitle": "A kọ́ fún àwọn ọmọ tí ó wà nínú ewu jùlọ láyé",
    "countriesSub": "Mímú gbogbo àwọn orílẹ̀-èdè UNICEF tí ó wà nínú ewu púpọ̀ pẹ̀lú àtìlẹ́yìn èdè àdúgbò",
    "moreCountries": "+51 orílẹ̀-èdè mìíràn",
    "ctaTitle": "Bẹ̀rẹ̀ sí dáàbò bo ọmọ rẹ nísinsìnyí",
    "ctaSub": "Yan orílẹ̀-èdè rẹ àti ọjọ́ orí ọmọ rẹ — gba ìdáhùn àti ètò ní èdè rẹ.",
    "chipNoAccount": "Kò sí àkọọ́lẹ̀ tó yẹ",
    "chipFree": "100% ọfẹ́",
    "chipLanguages": "55 èdè",
    "notMedical": "Kì í ṣe àropo fún ìmọ̀ràn ìṣègùn.",
    "language": "Èdè",
    "country": "Orílẹ̀-èdè",
    "childAge": "Ọjọ́ orí ọmọ",
    "checkNow": "Ṣàyẹ̀wò nísinsìnyí",
    "checking": "Ṣíṣàyẹ̀wò…",
    "tapMicSpeak": "Fọwọ́ tẹ gbohungbohun kí o sì sọ̀rọ̀ ní èdè rẹ",
    "recording": "Gbígbọ́… fọwọ́ tẹ gbohungbohun lẹ́ẹ̀kan sí nígbà tó o bá parí",
    "listen": "Gbọ́",
    "stop": "Dúró",
    "typeOrSpeak": "Tẹ níbí, tàbí fọwọ́ tẹ gbohungbohun kí o sì sọ̀rọ̀",
    "send": "Ránṣẹ́",
    "riskLow": "Ọmọ rẹ wà láìléwu nísinsìnyí.",
    "riskMedium": "Ṣọ́ra. Ṣọ́ ọmọ rẹ.",
    "riskHigh": "Ewu. Jẹ́ kí ọmọ rẹ wà nínú ilé àti láìléwu.",
    "riskCritical": "EWU PÚPỌ̀! Gba ìrànlọ́wọ́ nísinsìnyí.",
    "heatLabel": "Ooru",
    "heatDanger": "Ooru pọ̀ jù fún àwọn ọmọ. Jẹ́ kí wọ́n tutu, fún wọn ní omi.",
    "heatOk": "Ooru náà dára fún àwọn ọmọ.",
    "sunLabel": "Oòrùn",
    "sunDanger": "Oòrùn náà gbóná gan-an. Jẹ́ kí àwọn ọmọ wà ní òjìji.",
    "sunOk": "Oòrùn náà dára.",
    "airLabel": "Afẹ́fẹ́",
    "airDanger": "Afẹ́fẹ́ náà burú. Jẹ́ kí àwọn ọmọ wà nínú ilé.",
    "airOk": "Afẹ́fẹ́ náà dára.",
    "rainLabel": "Òjò",
    "rainDanger": "Òjò líle. Omi lè gbéga. Lọ sí ibi gíga, ibi ààbò.",
    "rainOk": "Òjò náà dára."
  },
  "ig": {
    "isMyChildInDanger": "Nwa m ọ nọ n'ihe egwu?",
    "myChildIsSick": "Nwa m na-arịa ọrịa",
    "sendAPhoto": "Ziga foto",
    "helpWithoutInternet": "Enyemaka na-enweghị ịntanetị",
    "worldMap": "Maapụ ụwa",
    "myChildren": "Ụmụ m",
    "about": "Banyere",
    "emergencyNow": "MBEREDE — nyere m aka ugbu a",
    "emergencyNumbers": "Nọmba mberede",
    "tapToCall": "Pịa nọmba ka ịkpọọ",
    "worksOffline": "Na-arụ ọrụ na-enweghị ịntanetị",
    "callNow": "Kpọọ ugbu a",
    "tap": "PỊA",
    "heroTitle": "Ichekwa ụmụaka pụọ n'ihe egwu ihu igwe",
    "heroSub": "Idei mmiri, okpomọkụ, oké ifufe, ikuku ọjọọ — lee ma nwa gị ọ dị mma na ihe ị ga-eme. N'asụsụ gị. N'efu.",
    "cardRiskDesc": "Hụ ihe egwu dị nso n'ụlọ gị, maka afọ nwa gị.",
    "cardHealthDesc": "Gwa anyị ihe na-eme — kwuo ma ọ bụ pịnye n'asụsụ gị.",
    "cardPhotoDesc": "Were foto ọkụ ọkụ, ọnya, idei mmiri ma ọ bụ anwụrụ ọkụ. Anyị ga-ele ya wee gwa gị ihe ị ga-eme.",
    "cardMapDesc": "Hụ ebe ihe egwu ụmụaka dị elu gburugburu ụwa.",
    "open": "Mepee",
    "statChildren": "Ụmụaka nọ n'ihe egwu ihu igwe 3+",
    "statStudents": "Ụmụ akwụkwọ agụmakwụkwọ ha kwụsịrị na 2024",
    "statDisplaced": "Nchụpụ ụmụaka kwa ụbọchị n'ihi ihu igwe",
    "statCountries": "Mba · asụsụ 55 akwadoro",
    "whyTitle": "Ihe mere anyị ji wuo nke a",
    "storiesTitle": "Ezi ọnọdụ mberede",
    "storiesSub": "Otu ezinụlọ si eji ClimaGuard mgbe ọ kacha mkpa",
    "countriesTitle": "Ewuru maka ụmụaka kacha nọrọ n'ihe egwu n'ụwa",
    "countriesSub": "Na-ekpuchi mba UNICEF niile nwere nnukwu ihe egwu na nkwado asụsụ obodo",
    "moreCountries": "+51 mba ndị ọzọ",
    "ctaTitle": "Bido chekwaa nwa gị ugbu a",
    "ctaSub": "Họrọ obodo gị na afọ nwa gị — nweta azịza na atụmatụ n'asụsụ gị.",
    "chipNoAccount": "Ọ dịghị akaụntụ achọrọ",
    "chipFree": "100% n'efu",
    "chipLanguages": "Asụsụ 55",
    "notMedical": "Ọ bụghị ihe nnọchi maka ndụmọdụ ahụike.",
    "language": "Asụsụ",
    "country": "Obodo",
    "childAge": "Afọ nwa",
    "checkNow": "Lelee ugbu a",
    "checking": "Na-elele…",
    "tapMicSpeak": "Pịa igwe okwu wee kwuo n'asụsụ gị",
    "recording": "Na-ege ntị… pịa igwe okwu ọzọ mgbe ịmechara",
    "listen": "Gee ntị",
    "stop": "Kwụsị",
    "typeOrSpeak": "Pịnye ebe a, ma ọ bụ pịa igwe okwu wee kwuo",
    "send": "Ziga",
    "riskLow": "Nwa gị dị mma ugbu a.",
    "riskMedium": "Kpachara anya. Lezie nwa gị anya.",
    "riskHigh": "Ihe egwu. Debe nwa gị n'ime ụlọ ma chekwaa ya.",
    "riskCritical": "Ọ DỊ EGWU! Nweta enyemaka ugbu a.",
    "heatLabel": "Okpomọkụ",
    "heatDanger": "Ọ na-ekpo oke ọkụ maka ụmụaka. Debe ha ka ha jụọ oyi, nye ha mmiri.",
    "heatOk": "Okpomọkụ dị mma maka ụmụaka.",
    "sunLabel": "Anyanwụ",
    "sunDanger": "Anyanwụ na-esi ike nke ukwuu. Debe ụmụaka na ndò.",
    "sunOk": "Anyanwụ dị mma.",
    "airLabel": "Ikuku",
    "airDanger": "Ikuku dị njọ. Debe ụmụaka n'ime ụlọ.",
    "airOk": "Ikuku dị mma.",
    "rainLabel": "Mmiri ozuzo",
    "rainDanger": "Oké mmiri ozuzo. Mmiri nwere ike ịrị elu. Gaa ebe dị elu, dị mma.",
    "rainOk": "Mmiri ozuzo dị mma."
  },
  "zu": {
    "isMyChildInDanger": "Ingabe ingane yami isengozini?",
    "myChildIsSick": "Ingane yami iyagula",
    "sendAPhoto": "Thumela isithombe",
    "helpWithoutInternet": "Usizo ngaphandle kwe-inthanethi",
    "worldMap": "Imephu yomhlaba",
    "myChildren": "Izingane zami",
    "about": "Mayelana",
    "emergencyNow": "ISIMO ESIPHUTHUMAYO — ngisize manje",
    "emergencyNumbers": "Izinombolo zezimo eziphuthumayo",
    "tapToCall": "Thepha inombolo ukuze ushaye",
    "worksOffline": "Isebenza ngaphandle kwe-inthanethi",
    "callNow": "Shaya manje",
    "tap": "THINTA",
    "heroTitle": "Ukugcina izingane ziphephile engozini yesimo sezulu",
    "heroSub": "Izikhukhula, ukushisa, iziphepho, umoya omubi — bona ukuthi ingane yakho iphephile yini nokuthi yenze njani. Ngolimi lwakho. Mahhala.",
    "cardRiskDesc": "Bona ingozi eduze kwekhaya lakho, ngeminyaka yengane yakho.",
    "cardHealthDesc": "Sitshele ukuthi yini engalungile — khuluma noma thayipha ngolimi lwakho.",
    "cardPhotoDesc": "Thatha isithombe sokuqubuka, isilonda, isikhukhula noma intuthu. Sizobheka sikutshele ukuthi wenzeni.",
    "cardMapDesc": "Bona ukuthi ingozi yezingane iphakeme kuphi emhlabeni jikelele.",
    "open": "Vula",
    "statChildren": "Izingane ezibhekene nezingozi zesimo sezulu ezi-3+",
    "statStudents": "Abafundi abaphazamiseke izifundo zabo ngo-2024",
    "statDisplaced": "Ukufuduka kwezingane ngosuku ngenxa yesimo sezulu",
    "statCountries": "Amazwe · Izilimi ezingama-55 ziyasekelwa",
    "whyTitle": "Kungani sakha lokhu",
    "storiesTitle": "Izimo zangempela eziphuthumayo",
    "storiesSub": "Indlela imindeni esebenzisa ngayo i-ClimaGuard lapho kubaluleke kakhulu",
    "countriesTitle": "Yakhelwe izingane ezisengozini kakhulu emhlabeni",
    "countriesSub": "Ihlanganisa wonke amazwe e-UNICEF asengozini enkulu ngokusekelwa kolimi lwendawo",
    "moreCountries": "+51 amazwe amaningi",
    "ctaTitle": "Qala ukuvikela ingane yakho manje",
    "ctaSub": "Khetha izwe lakho neminyaka yengane yakho — thola impendulo nohlelo ngolimi lwakho.",
    "chipNoAccount": "Ayikho i-akhawunti edingekayo",
    "chipFree": "100% mahhala",
    "chipLanguages": "Izilimi ezingama-55",
    "notMedical": "Akuyona indawo yeseluleko sezokwelapha.",
    "language": "Ulimi",
    "country": "Izwe",
    "childAge": "Iminyaka yengane",
    "checkNow": "Hlola manje",
    "checking": "Ihlola…",
    "tapMicSpeak": "Thepha imakrofoni bese ukhuluma ngolimi lwakho",
    "recording": "Iyalalela… thepha imakrofoni futhi uma usuqedile",
    "listen": "Lalela",
    "stop": "Misa",
    "typeOrSpeak": "Thayipha lapha, noma thepha imakrofoni bese ukhuluma",
    "send": "Thumela",
    "riskLow": "Ingane yakho iphephile okwamanje.",
    "riskMedium": "Qaphela. Bheka ingane yakho.",
    "riskHigh": "Ingozi. Gcina ingane yakho ngaphakathi iphephile.",
    "riskCritical": "KUYINGOZI KAKHULU! Thola usizo manje.",
    "heatLabel": "Ukushisa",
    "heatDanger": "Kushisa kakhulu ezinganeni. Zigcine zipholile, zinike amanzi.",
    "heatOk": "Ukushisa kulungile ezinganeni.",
    "sunLabel": "Ilanga",
    "sunDanger": "Ilanga libalele kakhulu. Gcina izingane emthunzini.",
    "sunOk": "Ilanga lilungile.",
    "airLabel": "Umoya",
    "airDanger": "Umoya mubi. Gcina izingane ngaphakathi.",
    "airOk": "Umoya ulungile.",
    "rainLabel": "Imvula",
    "rainDanger": "Imvula enamandla. Amanzi angase akhuphuke. Hamba uye endaweni ephakeme, ephephile.",
    "rainOk": "Imvula ilungile."
  },
  "af": {
    "isMyChildInDanger": "Is my kind in gevaar?",
    "myChildIsSick": "My kind is siek",
    "sendAPhoto": "Stuur 'n foto",
    "helpWithoutInternet": "Hulp sonder internet",
    "worldMap": "Wêreldkaart",
    "myChildren": "My kinders",
    "about": "Oor",
    "emergencyNow": "NOODGEVAL — help my nou",
    "emergencyNumbers": "Noodnommers",
    "tapToCall": "Tik 'n nommer om te bel",
    "worksOffline": "Werk sonder internet",
    "callNow": "Bel nou",
    "tap": "TIK",
    "heroTitle": "Hou kinders veilig teen weergevaar",
    "heroSub": "Vloede, hitte, storms, slegte lug — kyk of jou kind veilig is en wat om te doen. In jou taal. Gratis.",
    "cardRiskDesc": "Sien die gevaar naby jou huis, vir jou kind se ouderdom.",
    "cardHealthDesc": "Vertel ons wat fout is — praat of tik in jou taal.",
    "cardPhotoDesc": "Neem 'n foto van 'n uitslag, wond, vloed of rook. Ons kyk daarna en sê vir jou wat om te doen.",
    "cardMapDesc": "Sien waar gevaar vir kinders hoog is regoor die wêreld.",
    "open": "Maak oop",
    "statChildren": "Kinders blootgestel aan 3+ klimaatgevare",
    "statStudents": "Studente met skoolopleiding ontwrig in 2024",
    "statDisplaced": "Kinderverplasing per dag as gevolg van klimaat",
    "statCountries": "Lande · 55 tale ondersteun",
    "whyTitle": "Hoekom ons dit gebou het",
    "storiesTitle": "Werklike noodsituasies",
    "storiesSub": "Hoe gesinne ClimaGuard gebruik wanneer dit die meeste saak maak",
    "countriesTitle": "Gebou vir die wêreld se kwesbaarste kinders",
    "countriesSub": "Dek alle UNICEF hoërisiko-lande met plaaslike taalondersteuning",
    "moreCountries": "+51 meer lande",
    "ctaTitle": "Begin nou jou kind beskerm",
    "ctaSub": "Kies jou land en jou kind se ouderdom — kry 'n antwoord en 'n plan in jou taal.",
    "chipNoAccount": "Geen rekening nodig nie",
    "chipFree": "100% gratis",
    "chipLanguages": "55 tale",
    "notMedical": "Nie 'n plaasvervanger vir mediese advies nie.",
    "language": "Taal",
    "country": "Land",
    "childAge": "Kind se ouderdom",
    "checkNow": "Kontroleer nou",
    "checking": "Besig om te kontroleer…",
    "tapMicSpeak": "Tik die mikrofoon en praat in jou taal",
    "recording": "Luister… tik weer die mikrofoon wanneer jy klaar is",
    "listen": "Luister",
    "stop": "Stop",
    "typeOrSpeak": "Tik hier, of tik die mikrofoon en praat",
    "send": "Stuur",
    "riskLow": "Jou kind is nou veilig.",
    "riskMedium": "Wees versigtig. Hou jou kind dop.",
    "riskHigh": "Gevaar. Hou jou kind binne en veilig.",
    "riskCritical": "BAIE GEVAARLIK! Kry nou hulp.",
    "heatLabel": "Hitte",
    "heatDanger": "Dit is te warm vir kinders. Hou hulle koel, gee water.",
    "heatOk": "Die hitte is reg vir kinders.",
    "sunLabel": "Son",
    "sunDanger": "Die son is baie sterk. Hou kinders in die skaduwee.",
    "sunOk": "Die son is reg.",
    "airLabel": "Lug",
    "airDanger": "Die lug is sleg. Hou kinders binne.",
    "airOk": "Die lug is reg.",
    "rainLabel": "Reën",
    "rainDanger": "Swaar reën. Water kan styg. Gaan na 'n hoë, veilige plek.",
    "rainOk": "Die reën is reg."
  },
  "mg": {
    "isMyChildInDanger": "Mety ho tandindomin-doza ve ny zanako?",
    "myChildIsSick": "Marary ny zanako",
    "sendAPhoto": "Alefaso sary",
    "helpWithoutInternet": "Fanampiana tsy misy internet",
    "worldMap": "Sarintany maneran-tany",
    "myChildren": "Ny zanako",
    "about": "Momba anay",
    "emergencyNow": "MAIKA — ampio aho izao",
    "emergencyNumbers": "Nomerao vonjy taitra",
    "tapToCall": "Tsindrio ny nomerao hiantsoana",
    "worksOffline": "Miasa na tsy misy internet aza",
    "callNow": "Antsoy izao",
    "tap": "TSINDRIO",
    "heroTitle": "Miaro ny ankizy amin'ny loza ateraky ny toetr'andro",
    "heroSub": "Tondra-drano, hafanana, rivo-doza, rivotra maloto — jereo raha azo antoka ny zanakao ary inona no tokony hatao. Amin'ny fiteninao. Maimaim-poana.",
    "cardRiskDesc": "Jereo ny loza manodidina ny tranonao, arakaraka ny taonan'ny zanakao.",
    "cardHealthDesc": "Lazao anay izay tsy mety — mitenena na manorata amin'ny fiteninao.",
    "cardPhotoDesc": "Makà sary ny maimaika, ratra, tondra-drano na setroka. Hojerenay izany ary holazainay aminao izay tokony hatao.",
    "cardMapDesc": "Jereo hoe aiza no tena mampidi-doza ho an'ny ankizy maneran-tany.",
    "open": "Sokafy",
    "statChildren": "Ankizy tratran'ny loza ara-toetr'andro 3+",
    "statStudents": "Mpianatra tapaka fianarana tamin'ny 2024",
    "statDisplaced": "Fifindran'ny ankizy isan'andro noho ny toetr'andro",
    "statCountries": "Firenena · Fiteny 55 tohanana",
    "whyTitle": "Nahoana no natsanganay ity",
    "storiesTitle": "Toe-javatra vonjy taitra tena izy",
    "storiesSub": "Ahoana no ampiasain'ny fianakaviana ny ClimaGuard rehefa tena ilaina izany",
    "countriesTitle": "Namboarina ho an'ireo ankizy marefo indrindra eran-tany",
    "countriesSub": "Mandrakotra ny firenena rehetra atahorana indrindra an'ny UNICEF miaraka amin'ny fanohanana amin'ny fiteny eo an-toerana",
    "moreCountries": "+51 firenena hafa",
    "ctaTitle": "Atombohy ny fiarovana ny zanakao izao",
    "ctaSub": "Fidio ny firenenao sy ny taonan'ny zanakao — mahazo valiny sy drafitra amin'ny fiteninao.",
    "chipNoAccount": "Tsy mila kaonty",
    "chipFree": "Maimaim-poana 100%",
    "chipLanguages": "Fiteny 55",
    "notMedical": "Tsy fanoloana torohevitra ara-pitsaboana.",
    "language": "Fiteny",
    "country": "Firenena",
    "childAge": "Taonan'ny zaza",
    "checkNow": "Jereo izao",
    "checking": "Mijery…",
    "tapMicSpeak": "Tsindrio ny mikrô ary mitenena amin'ny fiteninao",
    "recording": "Mihaino… tsindrio indray ny mikrô rehefa vita",
    "listen": "Mihainoa",
    "stop": "Ajanony",
    "typeOrSpeak": "Manorata eto, na tsindrio ny mikrô ary mitenena",
    "send": "Alefaso",
    "riskLow": "Azo antoka ny zanakao amin'izao fotoana izao.",
    "riskMedium": "Mitandrema. Tandremo ny zanakao.",
    "riskHigh": "Loza. Ataovy ao an-trano sy azo antoka ny zanakao.",
    "riskCritical": "TENA MAMPIDI-DOZA! Mitadiava fanampiana izao.",
    "heatLabel": "Hafanana",
    "heatDanger": "Mafana loatra ho an'ny ankizy. Ataovy mangatsiaka izy ireo, omeo rano.",
    "heatOk": "Mety tsara ny hafanana ho an'ny ankizy.",
    "sunLabel": "Masoandro",
    "sunDanger": "Mafy be ny masoandro. Ataovy ao anaty alokaloka ny ankizy.",
    "sunOk": "Mety tsara ny masoandro.",
    "airLabel": "Rivotra",
    "airDanger": "Ratsy ny rivotra. Ataovy ao an-trano ny ankizy.",
    "airOk": "Mety tsara ny rivotra.",
    "rainLabel": "Orana",
    "rainDanger": "Orana be. Mety hiakatra ny rano. Mankanesa any amin'ny toerana avo sy azo antoka.",
    "rainOk": "Mety tsara ny orana."
  },
  "ms": {
    "isMyChildInDanger": "Adakah anak saya dalam bahaya?",
    "myChildIsSick": "Anak saya sakit",
    "sendAPhoto": "Hantar gambar",
    "helpWithoutInternet": "Bantuan tanpa internet",
    "worldMap": "Peta dunia",
    "myChildren": "Anak-anak saya",
    "about": "Tentang",
    "emergencyNow": "KECEMASAN — bantu saya sekarang",
    "emergencyNumbers": "Nombor kecemasan",
    "tapToCall": "Sentuh nombor untuk menelefon",
    "worksOffline": "Berfungsi tanpa internet",
    "callNow": "Telefon sekarang",
    "tap": "TEKAN",
    "heroTitle": "Menjaga kanak-kanak selamat daripada bahaya cuaca",
    "heroSub": "Banjir, panas, ribut, udara buruk — lihat jika anak anda selamat dan apa yang perlu dilakukan. Dalam bahasa anda. Percuma.",
    "cardRiskDesc": "Lihat bahaya berhampiran rumah anda, untuk umur anak anda.",
    "cardHealthDesc": "Beritahu kami apa yang salah — bercakap atau menaip dalam bahasa anda.",
    "cardPhotoDesc": "Ambil gambar ruam, luka, banjir atau asap. Kami melihatnya dan memberitahu anda apa yang perlu dilakukan.",
    "cardMapDesc": "Lihat di mana bahaya untuk kanak-kanak tinggi di seluruh dunia.",
    "open": "Buka",
    "statChildren": "Kanak-kanak terdedah kepada 3+ bahaya iklim",
    "statStudents": "Pelajar dengan persekolahan terganggu pada 2024",
    "statDisplaced": "Perpindahan kanak-kanak setiap hari akibat iklim",
    "statCountries": "Negara · 55 bahasa disokong",
    "whyTitle": "Mengapa kami membina ini",
    "storiesTitle": "Situasi kecemasan sebenar",
    "storiesSub": "Bagaimana keluarga menggunakan ClimaGuard apabila ia paling penting",
    "countriesTitle": "Dibina untuk kanak-kanak paling terdedah di dunia",
    "countriesSub": "Meliputi semua negara berisiko tinggi UNICEF dengan sokongan bahasa tempatan",
    "moreCountries": "+51 negara lagi",
    "ctaTitle": "Mula melindungi anak anda sekarang",
    "ctaSub": "Pilih negara anda dan umur anak anda — dapatkan jawapan dan pelan dalam bahasa anda.",
    "chipNoAccount": "Tiada akaun diperlukan",
    "chipFree": "100% percuma",
    "chipLanguages": "55 bahasa",
    "notMedical": "Bukan pengganti nasihat perubatan.",
    "language": "Bahasa",
    "country": "Negara",
    "childAge": "Umur anak",
    "checkNow": "Semak sekarang",
    "checking": "Menyemak…",
    "tapMicSpeak": "Sentuh mikrofon dan bercakap dalam bahasa anda",
    "recording": "Mendengar… sentuh mikrofon sekali lagi apabila anda selesai",
    "listen": "Dengar",
    "stop": "Berhenti",
    "typeOrSpeak": "Taip di sini, atau sentuh mikrofon dan bercakap",
    "send": "Hantar",
    "riskLow": "Anak anda selamat sekarang.",
    "riskMedium": "Berhati-hati. Perhatikan anak anda.",
    "riskHigh": "Bahaya. Pastikan anak anda di dalam dan selamat.",
    "riskCritical": "SANGAT BERBAHAYA! Dapatkan bantuan sekarang.",
    "heatLabel": "Panas",
    "heatDanger": "Terlalu panas untuk kanak-kanak. Pastikan mereka sejuk, berikan air.",
    "heatOk": "Panasnya okay untuk kanak-kanak.",
    "sunLabel": "Matahari",
    "sunDanger": "Matahari sangat terik. Pastikan kanak-kanak di tempat teduh.",
    "sunOk": "Matahari okay.",
    "airLabel": "Udara",
    "airDanger": "Udara buruk. Pastikan kanak-kanak di dalam.",
    "airOk": "Udara okay.",
    "rainLabel": "Hujan",
    "rainDanger": "Hujan lebat. Air mungkin naik. Pergi ke tempat tinggi yang selamat.",
    "rainOk": "Hujan okay."
  }
};
