// Localized UI chrome strings — the buttons, labels and plain-language
// sentences a parent must be able to read BEFORE any AI call happens.
// The AI already answers in 55 languages; this file makes the path to the AI
// (navigation, mic prompt, emergency button, risk sentences, home page copy)
// readable too.
//
// Written for low-literacy readers: short sentences, everyday words, no
// technical terms ("Calculate", "Vision", "AQI", "offline" are banned here).
// Coverage: every default language of the 66 UNICEF high-risk countries plus
// major refugee/migrant languages; the remaining selectable languages are
// filled in by UI_STRINGS_AUTO (AI-generated) and a runtime cache; English is
// the final fallback.

import { UI_STRINGS_AUTO } from "./uiStringsAuto";

export type UIStrings = {
  // Plain-language navigation (per parent feedback: name the need, not the tool)
  isMyChildInDanger: string; // → /dashboard  (was "Calculate Risk")
  myChildIsSick: string;     // → /health     (was "Health Advisor")
  sendAPhoto: string;        // → /vision     (was "Vision Analyzer")
  helpWithoutInternet: string; // → /offline-guide (was "Offline Guide")
  worldMap: string;
  myChildren: string;
  about: string;
  // Emergency
  emergencyNow: string;      // the one big button
  emergencyNumbers: string;
  tapToCall: string;
  worksOffline: string;
  callNow: string;
  tap: string;            // short word on the call button ("TAP"), + pointing hand
  // Home hero + tool cards
  heroTitle: string;
  heroSub: string;
  cardRiskDesc: string;
  cardHealthDesc: string;
  cardPhotoDesc: string;
  cardMapDesc: string;
  open: string;
  // Home stats
  statChildren: string;
  statStudents: string;
  statDisplaced: string;
  statCountries: string;
  // Home sections + CTA + footer
  whyTitle: string;
  storiesTitle: string;
  storiesSub: string;
  countriesTitle: string;
  countriesSub: string;
  moreCountries: string;
  ctaTitle: string;
  ctaSub: string;
  chipNoAccount: string;
  chipFree: string;
  chipLanguages: string;
  notMedical: string;
  // Form labels
  language: string;
  country: string;
  childAge: string;
  checkNow: string;
  checking: string;
  // Voice + read-aloud
  tapMicSpeak: string;
  recording: string;
  listen: string;
  stop: string;
  typeOrSpeak: string;
  send: string;
  // One-sentence risk meaning (color badge + this sentence, numbers optional)
  riskLow: string;
  riskMedium: string;
  riskHigh: string;
  riskCritical: string;
  // Plain weather sentences
  heatLabel: string; heatDanger: string; heatOk: string;
  sunLabel: string;  sunDanger: string;  sunOk: string;
  airLabel: string;  airDanger: string;  airOk: string;
  rainLabel: string; rainDanger: string; rainOk: string;
};

// Persian is defined once and reused for Dari (prs) — the written registers
// are close enough for short safety sentences.
const FA: UIStrings = {
  isMyChildInDanger: "آیا کودکم در خطر است؟",
  myChildIsSick: "کودکم بیمار است",
  sendAPhoto: "عکس بفرستید",
  helpWithoutInternet: "کمک بدون اینترنت",
  worldMap: "نقشه جهان",
  myChildren: "کودکان من",
  about: "درباره ما",
  emergencyNow: "اضطراری — همین حالا کمکم کنید",
  emergencyNumbers: "شماره‌های اضطراری",
  tapToCall: "برای تماس روی شماره بزنید",
  worksOffline: "بدون اینترنت هم کار می‌کند",
  callNow: "همین حالا تماس بگیرید",
  tap: "بزنید",
  heroTitle: "محافظت از کودکان در برابر خطرات آب‌وهوا",
  heroSub: "سیل، گرما، طوفان، هوای آلوده — ببینید کودک شما در امان است یا نه و چه باید کرد. به زبان شما. رایگان.",
  cardRiskDesc: "خطر نزدیک خانه‌تان را بر اساس سن کودک ببینید.",
  cardHealthDesc: "بگویید مشکل چیست — به زبان خود صحبت کنید یا بنویسید.",
  cardPhotoDesc: "از جوش، زخم، سیل یا دود عکس بگیرید. ما نگاه می‌کنیم و می‌گوییم چه کنید.",
  cardMapDesc: "ببینید خطر برای کودکان در کجای جهان زیاد است.",
  open: "باز کنید",
  statChildren: "کودکان در معرض ۳+ خطر اقلیمی",
  statStudents: "دانش‌آموزانی که در ۲۰۲۴ درسشان مختل شد",
  statDisplaced: "کودکانی که هر روز به‌خاطر اقلیم آواره می‌شوند",
  statCountries: "کشور · پشتیبانی از ۵۵ زبان",
  whyTitle: "چرا این را ساختیم",
  storiesTitle: "موقعیت‌های اضطراری واقعی",
  storiesSub: "خانواده‌ها در لحظه‌های سخت چگونه از ClimaGuard استفاده می‌کنند",
  countriesTitle: "ساخته‌شده برای آسیب‌پذیرترین کودکان جهان",
  countriesSub: "همه کشورهای پرخطر UNICEF، به زبان محلی",
  moreCountries: "+۵۱ کشور دیگر",
  ctaTitle: "همین حالا محافظت از کودکتان را شروع کنید",
  ctaSub: "کشور و سن کودک را انتخاب کنید — پاسخ و برنامه را به زبان خود بگیرید.",
  chipNoAccount: "بدون نیاز به حساب",
  chipFree: "کاملاً رایگان",
  chipLanguages: "۵۵ زبان",
  notMedical: "جایگزین توصیه پزشک نیست.",
  language: "زبان",
  country: "کشور",
  childAge: "سن کودک",
  checkNow: "همین حالا بررسی کنید",
  checking: "در حال بررسی…",
  tapMicSpeak: "روی میکروفون بزنید و به زبان خود صحبت کنید",
  recording: "در حال شنیدن… وقتی تمام شد دوباره روی میکروفون بزنید",
  listen: "بشنوید",
  stop: "توقف",
  typeOrSpeak: "اینجا بنویسید، یا روی میکروفون بزنید و صحبت کنید",
  send: "ارسال",
  riskLow: "کودک شما اکنون در امان است.",
  riskMedium: "مراقب باشید. کودک را زیر نظر داشته باشید.",
  riskHigh: "خطر. کودک را در خانه و در امان نگه دارید.",
  riskCritical: "بسیار خطرناک! همین حالا کمک بگیرید.",
  heatLabel: "گرما", heatDanger: "هوا برای کودکان بسیار گرم است. خنکشان کنید و آب بدهید.", heatOk: "گرما اکنون مشکلی ندارد.",
  sunLabel: "آفتاب", sunDanger: "آفتاب بسیار شدید است. کودکان را در سایه نگه دارید.", sunOk: "آفتاب اکنون مشکلی ندارد.",
  airLabel: "هوا", airDanger: "هوا آلوده است. کودکان را در خانه نگه دارید.", airOk: "هوا اکنون خوب است.",
  rainLabel: "باران", rainDanger: "باران شدید. آب ممکن است بالا بیاید. به جای بلند و امن بروید.", rainOk: "باران اکنون مشکلی ندارد.",
};

export const UI_STRINGS: Record<string, UIStrings> = {
  en: {
    isMyChildInDanger: "Is my child in danger?",
    myChildIsSick: "My child is sick",
    sendAPhoto: "Send a photo",
    helpWithoutInternet: "Help without internet",
    worldMap: "World map",
    myChildren: "My children",
    about: "About",
    emergencyNow: "EMERGENCY — help me now",
    emergencyNumbers: "Emergency numbers",
    tapToCall: "Tap a number to call",
    worksOffline: "Works without internet",
    callNow: "Call now",
    tap: "TAP",
    heroTitle: "Keeping children safe from weather danger",
    heroSub: "Floods, heat, storms, bad air — see if your child is safe and what to do. In your language. Free.",
    cardRiskDesc: "See the danger near your home, for your child's age.",
    cardHealthDesc: "Tell us what is wrong — speak or type in your language.",
    cardPhotoDesc: "Take a photo of a rash, wound, flood or smoke. We look at it and tell you what to do.",
    cardMapDesc: "See where danger for children is high around the world.",
    open: "Open",
    statChildren: "Children exposed to 3+ climate hazards",
    statStudents: "Students with schooling disrupted in 2024",
    statDisplaced: "Child displacements per day from climate",
    statCountries: "Countries · 55 languages supported",
    whyTitle: "Why we built this",
    storiesTitle: "Real emergency situations",
    storiesSub: "How families use ClimaGuard when it matters most",
    countriesTitle: "Built for the world's most vulnerable children",
    countriesSub: "Covering all UNICEF high-risk countries with local language support",
    moreCountries: "+51 more countries",
    ctaTitle: "Start protecting your child now",
    ctaSub: "Choose your country and your child's age — get an answer and a plan in your language.",
    chipNoAccount: "No account needed",
    chipFree: "100% free",
    chipLanguages: "55 languages",
    notMedical: "Not a substitute for medical advice.",
    language: "Language",
    country: "Country",
    childAge: "Child's age",
    checkNow: "Check now",
    checking: "Checking…",
    tapMicSpeak: "Tap the microphone and speak in your language",
    recording: "Listening… tap the microphone again when you finish",
    listen: "Listen",
    stop: "Stop",
    typeOrSpeak: "Type here, or tap the microphone and speak",
    send: "Send",
    riskLow: "Your child is safe right now.",
    riskMedium: "Be careful. Watch your child.",
    riskHigh: "Danger. Keep your child inside and safe.",
    riskCritical: "VERY DANGEROUS! Get help now.",
    heatLabel: "Heat", heatDanger: "It is too hot for children. Keep them cool, give water.", heatOk: "The heat is okay for children.",
    sunLabel: "Sun", sunDanger: "The sun is very strong. Keep children in the shade.", sunOk: "The sun is okay.",
    airLabel: "Air", airDanger: "The air is bad. Keep children inside.", airOk: "The air is okay.",
    rainLabel: "Rain", rainDanger: "Heavy rain. Water may rise. Go to a high, safe place.", rainOk: "The rain is okay.",
  },
  bn: {
    isMyChildInDanger: "আমার শিশু কি বিপদে আছে?",
    myChildIsSick: "আমার শিশু অসুস্থ",
    sendAPhoto: "ছবি পাঠান",
    helpWithoutInternet: "ইন্টারনেট ছাড়া সাহায্য",
    worldMap: "বিশ্ব মানচিত্র",
    myChildren: "আমার শিশুরা",
    about: "পরিচিতি",
    emergencyNow: "জরুরি — এখনই সাহায্য চাই",
    emergencyNumbers: "জরুরি ফোন নম্বর",
    tapToCall: "নম্বরে চাপ দিলে ফোন যাবে",
    worksOffline: "ইন্টারনেট ছাড়াও কাজ করে",
    callNow: "এখনই ফোন করুন",
    tap: "চাপ দিন",
    heroTitle: "আবহাওয়ার বিপদ থেকে শিশুদের নিরাপদ রাখুন",
    heroSub: "বন্যা, গরম, ঝড়, খারাপ বাতাস — আপনার শিশু নিরাপদ কি না দেখুন, কী করবেন জানুন। আপনার ভাষায়। বিনামূল্যে।",
    cardRiskDesc: "আপনার এলাকায় শিশুর জন্য কী বিপদ আছে দেখুন।",
    cardHealthDesc: "কী সমস্যা বলুন — নিজের ভাষায় বলুন বা লিখুন।",
    cardPhotoDesc: "র‍্যাশ, ক্ষত, বন্যা বা ধোঁয়ার ছবি তুলুন। আমরা দেখে বলব কী করতে হবে।",
    cardMapDesc: "বিশ্বের কোথায় শিশুদের জন্য বিপদ বেশি দেখুন।",
    open: "খুলুন",
    statChildren: "৩+ জলবায়ু বিপদের মুখে থাকা শিশু",
    statStudents: "২০২৪ সালে পড়াশোনা ব্যাহত হওয়া শিক্ষার্থী",
    statDisplaced: "জলবায়ুর কারণে প্রতিদিন ঘরছাড়া শিশু",
    statCountries: "দেশ · ৫৫টি ভাষায় সহায়তা",
    whyTitle: "কেন আমরা এটা বানিয়েছি",
    storiesTitle: "সত্যিকারের জরুরি ঘটনা",
    storiesSub: "বিপদের সময় পরিবারগুলো কীভাবে ClimaGuard ব্যবহার করে",
    countriesTitle: "বিশ্বের সবচেয়ে ঝুঁকিতে থাকা শিশুদের জন্য তৈরি",
    countriesSub: "UNICEF-এর সব উচ্চ-ঝুঁকির দেশ, স্থানীয় ভাষায়",
    moreCountries: "+ আরও ৫১টি দেশ",
    ctaTitle: "এখনই আপনার শিশুকে রক্ষা করা শুরু করুন",
    ctaSub: "দেশ ও শিশুর বয়স বেছে নিন — নিজের ভাষায় উত্তর ও করণীয় পান।",
    chipNoAccount: "অ্যাকাউন্ট লাগে না",
    chipFree: "সম্পূর্ণ বিনামূল্যে",
    chipLanguages: "৫৫টি ভাষা",
    notMedical: "এটি ডাক্তারের পরামর্শের বিকল্প নয়।",
    language: "ভাষা",
    country: "দেশ",
    childAge: "শিশুর বয়স",
    checkNow: "এখনই দেখুন",
    checking: "দেখা হচ্ছে…",
    tapMicSpeak: "মাইকে চাপ দিন, নিজের ভাষায় বলুন",
    recording: "শোনা হচ্ছে… বলা শেষ হলে আবার মাইকে চাপ দিন",
    listen: "শুনুন",
    stop: "থামুন",
    typeOrSpeak: "এখানে লিখুন, অথবা মাইকে চাপ দিয়ে বলুন",
    send: "পাঠান",
    riskLow: "আপনার শিশু এখন নিরাপদ।",
    riskMedium: "সাবধান থাকুন। শিশুর দিকে খেয়াল রাখুন।",
    riskHigh: "বিপদ। শিশুকে ঘরের ভিতরে নিরাপদে রাখুন।",
    riskCritical: "খুব বিপজ্জনক! এখনই সাহায্য নিন।",
    heatLabel: "গরম", heatDanger: "শিশুদের জন্য খুব বেশি গরম। ঠান্ডা রাখুন, পানি দিন।", heatOk: "গরম এখন শিশুদের জন্য সহনীয়।",
    sunLabel: "রোদ", sunDanger: "রোদ খুব কড়া। শিশুদের ছায়ায় রাখুন।", sunOk: "রোদ এখন ঠিক আছে।",
    airLabel: "বাতাস", airDanger: "বাতাস খারাপ। শিশুদের ঘরের ভিতরে রাখুন।", airOk: "বাতাস এখন ঠিক আছে।",
    rainLabel: "বৃষ্টি", rainDanger: "ভারী বৃষ্টি। পানি বাড়তে পারে। উঁচু নিরাপদ জায়গায় যান।", rainOk: "বৃষ্টি এখন ঠিক আছে।",
  },
  hi: {
    isMyChildInDanger: "क्या मेरा बच्चा खतरे में है?",
    myChildIsSick: "मेरा बच्चा बीमार है",
    sendAPhoto: "फोटो भेजें",
    helpWithoutInternet: "बिना इंटरनेट मदद",
    worldMap: "विश्व नक्शा",
    myChildren: "मेरे बच्चे",
    about: "परिचय",
    emergencyNow: "आपातकाल — अभी मदद चाहिए",
    emergencyNumbers: "आपातकालीन फोन नंबर",
    tapToCall: "नंबर दबाते ही कॉल लगेगा",
    worksOffline: "बिना इंटरनेट भी चलता है",
    callNow: "अभी कॉल करें",
    tap: "दबाएँ",
    heroTitle: "मौसम के खतरों से बच्चों को सुरक्षित रखें",
    heroSub: "बाढ़, गर्मी, तूफान, खराब हवा — देखें कि आपका बच्चा सुरक्षित है या नहीं, और क्या करें। आपकी भाषा में। मुफ्त।",
    cardRiskDesc: "देखें कि आपके इलाके में बच्चे के लिए क्या खतरा है।",
    cardHealthDesc: "बताएँ क्या तकलीफ है — अपनी भाषा में बोलें या लिखें।",
    cardPhotoDesc: "दाने, घाव, बाढ़ या धुएँ की फोटो लें। हम देखकर बताएँगे क्या करना है।",
    cardMapDesc: "देखें दुनिया में कहाँ बच्चों के लिए खतरा ज़्यादा है।",
    open: "खोलें",
    statChildren: "3+ जलवायु खतरों का सामना करते बच्चे",
    statStudents: "2024 में पढ़ाई बाधित हुए छात्र",
    statDisplaced: "जलवायु से रोज़ बेघर होते बच्चे",
    statCountries: "देश · 55 भाषाओं में सहायता",
    whyTitle: "हमने यह क्यों बनाया",
    storiesTitle: "असली आपातकालीन घटनाएँ",
    storiesSub: "मुसीबत में परिवार ClimaGuard का इस्तेमाल कैसे करते हैं",
    countriesTitle: "दुनिया के सबसे जोखिम वाले बच्चों के लिए बना",
    countriesSub: "UNICEF के सभी उच्च-जोखिम देश, स्थानीय भाषा में",
    moreCountries: "+51 और देश",
    ctaTitle: "अभी अपने बच्चे की सुरक्षा शुरू करें",
    ctaSub: "देश और बच्चे की उम्र चुनें — अपनी भाषा में जवाब और उपाय पाएँ।",
    chipNoAccount: "खाता ज़रूरी नहीं",
    chipFree: "पूरी तरह मुफ्त",
    chipLanguages: "55 भाषाएँ",
    notMedical: "यह डॉक्टर की सलाह का विकल्प नहीं है।",
    language: "भाषा",
    country: "देश",
    childAge: "बच्चे की उम्र",
    checkNow: "अभी जांचें",
    checking: "जांच हो रही है…",
    tapMicSpeak: "माइक दबाएँ, अपनी भाषा में बोलें",
    recording: "सुन रहे हैं… बोलना खत्म होने पर फिर माइक दबाएँ",
    listen: "सुनें",
    stop: "रोकें",
    typeOrSpeak: "यहाँ लिखें, या माइक दबाकर बोलें",
    send: "भेजें",
    riskLow: "आपका बच्चा अभी सुरक्षित है।",
    riskMedium: "सावधान रहें। बच्चे पर नज़र रखें।",
    riskHigh: "खतरा। बच्चे को घर के अंदर सुरक्षित रखें।",
    riskCritical: "बहुत खतरनाक! अभी मदद लें।",
    heatLabel: "गर्मी", heatDanger: "बच्चों के लिए बहुत गर्मी है। ठंडा रखें, पानी दें।", heatOk: "गर्मी अभी ठीक है।",
    sunLabel: "धूप", sunDanger: "धूप बहुत तेज़ है। बच्चों को छाया में रखें।", sunOk: "धूप अभी ठीक है।",
    airLabel: "हवा", airDanger: "हवा खराब है। बच्चों को घर के अंदर रखें।", airOk: "हवा अभी ठीक है।",
    rainLabel: "बारिश", rainDanger: "भारी बारिश। पानी बढ़ सकता है। ऊँची सुरक्षित जगह जाएँ।", rainOk: "बारिश अभी ठीक है।",
  },
  ur: {
    isMyChildInDanger: "کیا میرا بچہ خطرے میں ہے؟",
    myChildIsSick: "میرا بچہ بیمار ہے",
    sendAPhoto: "تصویر بھیجیں",
    helpWithoutInternet: "انٹرنیٹ کے بغیر مدد",
    worldMap: "دنیا کا نقشہ",
    myChildren: "میرے بچے",
    about: "تعارف",
    emergencyNow: "ایمرجنسی — ابھی مدد چاہیے",
    emergencyNumbers: "ایمرجنسی فون نمبر",
    tapToCall: "نمبر دبائیں تو کال لگے گی",
    worksOffline: "انٹرنیٹ کے بغیر بھی چلتا ہے",
    callNow: "ابھی کال کریں",
    tap: "دبائیں",
    heroTitle: "موسم کے خطروں سے بچوں کو محفوظ رکھیں",
    heroSub: "سیلاب، گرمی، طوفان، خراب ہوا — دیکھیں کہ آپ کا بچہ محفوظ ہے یا نہیں، اور کیا کریں۔ آپ کی زبان میں۔ مفت۔",
    cardRiskDesc: "دیکھیں آپ کے علاقے میں بچے کے لیے کیا خطرہ ہے۔",
    cardHealthDesc: "بتائیں کیا تکلیف ہے — اپنی زبان میں بولیں یا لکھیں۔",
    cardPhotoDesc: "دانوں، زخم، سیلاب یا دھوئیں کی تصویر لیں۔ ہم دیکھ کر بتائیں گے کیا کرنا ہے۔",
    cardMapDesc: "دیکھیں دنیا میں کہاں بچوں کے لیے خطرہ زیادہ ہے۔",
    open: "کھولیں",
    statChildren: "3+ موسمیاتی خطرات کا سامنا کرتے بچے",
    statStudents: "2024 میں تعلیم متاثر ہونے والے طلبہ",
    statDisplaced: "موسمیات کی وجہ سے روزانہ بے گھر بچے",
    statCountries: "ممالک · 55 زبانوں میں مدد",
    whyTitle: "ہم نے یہ کیوں بنایا",
    storiesTitle: "حقیقی ہنگامی واقعات",
    storiesSub: "مشکل وقت میں خاندان ClimaGuard کیسے استعمال کرتے ہیں",
    countriesTitle: "دنیا کے سب سے زیادہ خطرے والے بچوں کے لیے",
    countriesSub: "UNICEF کے تمام زیادہ خطرے والے ممالک، مقامی زبان میں",
    moreCountries: "+51 مزید ممالک",
    ctaTitle: "ابھی اپنے بچے کی حفاظت شروع کریں",
    ctaSub: "ملک اور بچے کی عمر چنیں — اپنی زبان میں جواب اور لائحہ عمل پائیں۔",
    chipNoAccount: "اکاؤنٹ کی ضرورت نہیں",
    chipFree: "بالکل مفت",
    chipLanguages: "55 زبانیں",
    notMedical: "یہ ڈاکٹر کے مشورے کا متبادل نہیں ہے۔",
    language: "زبان",
    country: "ملک",
    childAge: "بچے کی عمر",
    checkNow: "ابھی دیکھیں",
    checking: "دیکھا جا رہا ہے…",
    tapMicSpeak: "مائیک دبائیں، اپنی زبان میں بولیں",
    recording: "سن رہے ہیں… بات ختم ہو تو دوبارہ مائیک دبائیں",
    listen: "سنیں",
    stop: "روکیں",
    typeOrSpeak: "یہاں لکھیں، یا مائیک دبا کر بولیں",
    send: "بھیجیں",
    riskLow: "آپ کا بچہ ابھی محفوظ ہے۔",
    riskMedium: "محتاط رہیں۔ بچے کا خیال رکھیں۔",
    riskHigh: "خطرہ۔ بچے کو گھر کے اندر محفوظ رکھیں۔",
    riskCritical: "بہت خطرناک! ابھی مدد لیں۔",
    heatLabel: "گرمی", heatDanger: "بچوں کے لیے بہت گرمی ہے۔ ٹھنڈا رکھیں، پانی دیں۔", heatOk: "گرمی ابھی ٹھیک ہے۔",
    sunLabel: "دھوپ", sunDanger: "دھوپ بہت تیز ہے۔ بچوں کو سائے میں رکھیں۔", sunOk: "دھوپ ابھی ٹھیک ہے۔",
    airLabel: "ہوا", airDanger: "ہوا خراب ہے۔ بچوں کو گھر کے اندر رکھیں۔", airOk: "ہوا ابھی ٹھیک ہے۔",
    rainLabel: "بارش", rainDanger: "تیز بارش۔ پانی بڑھ سکتا ہے۔ اونچی محفوظ جگہ جائیں۔", rainOk: "بارش ابھی ٹھیک ہے۔",
  },
  ar: {
    isMyChildInDanger: "هل طفلي في خطر؟",
    myChildIsSick: "طفلي مريض",
    sendAPhoto: "أرسل صورة",
    helpWithoutInternet: "مساعدة بدون إنترنت",
    worldMap: "خريطة العالم",
    myChildren: "أطفالي",
    about: "من نحن",
    emergencyNow: "طوارئ — أحتاج مساعدة الآن",
    emergencyNumbers: "أرقام الطوارئ",
    tapToCall: "اضغط على الرقم للاتصال",
    worksOffline: "يعمل بدون إنترنت",
    callNow: "اتصل الآن",
    tap: "اضغط",
    heroTitle: "حماية الأطفال من أخطار الطقس",
    heroSub: "فيضانات، حر شديد، عواصف، هواء ملوث — اعرف إن كان طفلك بأمان وماذا تفعل. بلغتك. مجانًا.",
    cardRiskDesc: "اعرف الخطر القريب من بيتك حسب عمر طفلك.",
    cardHealthDesc: "أخبرنا ما المشكلة — تكلم أو اكتب بلغتك.",
    cardPhotoDesc: "صوّر الطفح أو الجرح أو الفيضان أو الدخان. نفحص الصورة ونخبرك ماذا تفعل.",
    cardMapDesc: "اعرف أين يشتد الخطر على الأطفال حول العالم.",
    open: "افتح",
    statChildren: "أطفال معرضون لثلاثة أخطار مناخية أو أكثر",
    statStudents: "طلاب تعطّل تعليمهم في 2024",
    statDisplaced: "أطفال يُهجَّرون يوميًا بسبب المناخ",
    statCountries: "دولة · دعم بـ55 لغة",
    whyTitle: "لماذا بنينا هذا",
    storiesTitle: "حالات طوارئ حقيقية",
    storiesSub: "كيف تستخدم العائلات ClimaGuard وقت الشدة",
    countriesTitle: "صُمم لأكثر أطفال العالم عرضة للخطر",
    countriesSub: "يغطي كل دول UNICEF عالية الخطورة باللغات المحلية",
    moreCountries: "+51 دولة أخرى",
    ctaTitle: "ابدأ حماية طفلك الآن",
    ctaSub: "اختر دولتك وعمر طفلك — تحصل على إجابة وخطة بلغتك.",
    chipNoAccount: "لا يحتاج حسابًا",
    chipFree: "مجاني تمامًا",
    chipLanguages: "55 لغة",
    notMedical: "ليس بديلاً عن استشارة الطبيب.",
    language: "اللغة",
    country: "الدولة",
    childAge: "عمر الطفل",
    checkNow: "افحص الآن",
    checking: "جارٍ الفحص…",
    tapMicSpeak: "اضغط على الميكروفون وتكلم بلغتك",
    recording: "نستمع… اضغط على الميكروفون مرة أخرى عند الانتهاء",
    listen: "استمع",
    stop: "أوقف",
    typeOrSpeak: "اكتب هنا، أو اضغط على الميكروفون وتكلم",
    send: "أرسل",
    riskLow: "طفلك بأمان الآن.",
    riskMedium: "كن حذرًا. راقب طفلك.",
    riskHigh: "خطر. أبقِ طفلك داخل البيت بأمان.",
    riskCritical: "خطر شديد! اطلب المساعدة الآن.",
    heatLabel: "الحر", heatDanger: "الجو حار جدًا على الأطفال. برّدهم وأعطهم ماء.", heatOk: "الحرارة مقبولة الآن.",
    sunLabel: "الشمس", sunDanger: "الشمس قوية جدًا. أبقِ الأطفال في الظل.", sunOk: "الشمس مقبولة الآن.",
    airLabel: "الهواء", airDanger: "الهواء ملوث. أبقِ الأطفال داخل البيت.", airOk: "الهواء جيد الآن.",
    rainLabel: "المطر", rainDanger: "مطر غزير. قد يرتفع الماء. اذهب إلى مكان مرتفع وآمن.", rainOk: "المطر مقبول الآن.",
  },
  fr: {
    isMyChildInDanger: "Mon enfant est-il en danger ?",
    myChildIsSick: "Mon enfant est malade",
    sendAPhoto: "Envoyer une photo",
    helpWithoutInternet: "Aide sans internet",
    worldMap: "Carte du monde",
    myChildren: "Mes enfants",
    about: "À propos",
    emergencyNow: "URGENCE — aidez-moi maintenant",
    emergencyNumbers: "Numéros d'urgence",
    tapToCall: "Touchez un numéro pour appeler",
    worksOffline: "Fonctionne sans internet",
    callNow: "Appeler maintenant",
    tap: "TOUCHEZ",
    heroTitle: "Protéger les enfants des dangers du climat",
    heroSub: "Inondations, chaleur, tempêtes, air pollué — vérifiez si votre enfant est en sécurité et que faire. Dans votre langue. Gratuit.",
    cardRiskDesc: "Voyez le danger près de chez vous, selon l'âge de votre enfant.",
    cardHealthDesc: "Dites-nous ce qui ne va pas — parlez ou écrivez dans votre langue.",
    cardPhotoDesc: "Photographiez une éruption, une blessure, une inondation ou de la fumée. Nous regardons et vous disons quoi faire.",
    cardMapDesc: "Voyez où le danger est élevé pour les enfants dans le monde.",
    open: "Ouvrir",
    statChildren: "Enfants exposés à 3+ risques climatiques",
    statStudents: "Élèves dont l'école a été perturbée en 2024",
    statDisplaced: "Enfants déplacés chaque jour par le climat",
    statCountries: "Pays · 55 langues prises en charge",
    whyTitle: "Pourquoi nous l'avons créé",
    storiesTitle: "Vraies situations d'urgence",
    storiesSub: "Comment les familles utilisent ClimaGuard quand ça compte",
    countriesTitle: "Conçu pour les enfants les plus vulnérables du monde",
    countriesSub: "Tous les pays à haut risque de l'UNICEF, en langue locale",
    moreCountries: "+51 autres pays",
    ctaTitle: "Commencez à protéger votre enfant maintenant",
    ctaSub: "Choisissez votre pays et l'âge de votre enfant — recevez une réponse et un plan dans votre langue.",
    chipNoAccount: "Sans compte",
    chipFree: "100 % gratuit",
    chipLanguages: "55 langues",
    notMedical: "Ne remplace pas un avis médical.",
    language: "Langue",
    country: "Pays",
    childAge: "Âge de l'enfant",
    checkNow: "Vérifier maintenant",
    checking: "Vérification…",
    tapMicSpeak: "Touchez le micro et parlez dans votre langue",
    recording: "On vous écoute… touchez encore le micro quand vous avez fini",
    listen: "Écouter",
    stop: "Arrêter",
    typeOrSpeak: "Écrivez ici, ou touchez le micro et parlez",
    send: "Envoyer",
    riskLow: "Votre enfant est en sécurité pour le moment.",
    riskMedium: "Soyez prudent. Surveillez votre enfant.",
    riskHigh: "Danger. Gardez votre enfant à l'intérieur, en sécurité.",
    riskCritical: "TRÈS DANGEREUX ! Cherchez de l'aide maintenant.",
    heatLabel: "Chaleur", heatDanger: "Il fait trop chaud pour les enfants. Rafraîchissez-les, donnez de l'eau.", heatOk: "La chaleur est supportable.",
    sunLabel: "Soleil", sunDanger: "Le soleil est très fort. Gardez les enfants à l'ombre.", sunOk: "Le soleil ne pose pas de problème.",
    airLabel: "Air", airDanger: "L'air est mauvais. Gardez les enfants à l'intérieur.", airOk: "L'air est bon.",
    rainLabel: "Pluie", rainDanger: "Pluie forte. L'eau peut monter. Allez vers un lieu haut et sûr.", rainOk: "La pluie ne pose pas de problème.",
  },
  es: {
    isMyChildInDanger: "¿Mi hijo está en peligro?",
    myChildIsSick: "Mi hijo está enfermo",
    sendAPhoto: "Enviar una foto",
    helpWithoutInternet: "Ayuda sin internet",
    worldMap: "Mapa mundial",
    myChildren: "Mis hijos",
    about: "Acerca de",
    emergencyNow: "EMERGENCIA — ayuda ahora",
    emergencyNumbers: "Números de emergencia",
    tapToCall: "Toque un número para llamar",
    worksOffline: "Funciona sin internet",
    callNow: "Llamar ahora",
    tap: "TOQUE",
    heroTitle: "Proteger a los niños de los peligros del clima",
    heroSub: "Inundaciones, calor, tormentas, aire contaminado — vea si su hijo está seguro y qué hacer. En su idioma. Gratis.",
    cardRiskDesc: "Vea el peligro cerca de su casa, según la edad de su hijo.",
    cardHealthDesc: "Cuéntenos qué pasa — hable o escriba en su idioma.",
    cardPhotoDesc: "Fotografíe un sarpullido, una herida, una inundación o humo. Lo revisamos y le decimos qué hacer.",
    cardMapDesc: "Vea dónde el peligro para los niños es alto en el mundo.",
    open: "Abrir",
    statChildren: "Niños expuestos a 3+ riesgos climáticos",
    statStudents: "Estudiantes con clases interrumpidas en 2024",
    statDisplaced: "Niños desplazados cada día por el clima",
    statCountries: "Países · 55 idiomas disponibles",
    whyTitle: "Por qué lo creamos",
    storiesTitle: "Emergencias reales",
    storiesSub: "Cómo las familias usan ClimaGuard cuando más importa",
    countriesTitle: "Hecho para los niños más vulnerables del mundo",
    countriesSub: "Todos los países de alto riesgo de UNICEF, en idioma local",
    moreCountries: "+51 países más",
    ctaTitle: "Empiece a proteger a su hijo ahora",
    ctaSub: "Elija su país y la edad de su hijo — reciba una respuesta y un plan en su idioma.",
    chipNoAccount: "Sin cuenta",
    chipFree: "100 % gratis",
    chipLanguages: "55 idiomas",
    notMedical: "No sustituye el consejo médico.",
    language: "Idioma",
    country: "País",
    childAge: "Edad del niño",
    checkNow: "Comprobar ahora",
    checking: "Comprobando…",
    tapMicSpeak: "Toque el micrófono y hable en su idioma",
    recording: "Escuchando… toque el micrófono otra vez al terminar",
    listen: "Escuchar",
    stop: "Detener",
    typeOrSpeak: "Escriba aquí, o toque el micrófono y hable",
    send: "Enviar",
    riskLow: "Su hijo está seguro ahora.",
    riskMedium: "Tenga cuidado. Vigile a su hijo.",
    riskHigh: "Peligro. Mantenga a su hijo dentro y seguro.",
    riskCritical: "¡MUY PELIGROSO! Busque ayuda ahora.",
    heatLabel: "Calor", heatDanger: "Hace demasiado calor para los niños. Refrésquelos y deles agua.", heatOk: "El calor está bien ahora.",
    sunLabel: "Sol", sunDanger: "El sol está muy fuerte. Mantenga a los niños a la sombra.", sunOk: "El sol está bien ahora.",
    airLabel: "Aire", airDanger: "El aire está malo. Mantenga a los niños dentro.", airOk: "El aire está bien ahora.",
    rainLabel: "Lluvia", rainDanger: "Lluvia fuerte. El agua puede subir. Vaya a un lugar alto y seguro.", rainOk: "La lluvia está bien ahora.",
  },
  pt: {
    isMyChildInDanger: "O meu filho está em perigo?",
    myChildIsSick: "O meu filho está doente",
    sendAPhoto: "Enviar uma foto",
    helpWithoutInternet: "Ajuda sem internet",
    worldMap: "Mapa do mundo",
    myChildren: "Os meus filhos",
    about: "Sobre",
    emergencyNow: "EMERGÊNCIA — preciso de ajuda agora",
    emergencyNumbers: "Números de emergência",
    tapToCall: "Toque num número para ligar",
    worksOffline: "Funciona sem internet",
    callNow: "Ligar agora",
    tap: "TOQUE",
    heroTitle: "Proteger as crianças dos perigos do clima",
    heroSub: "Cheias, calor, tempestades, ar poluído — veja se o seu filho está seguro e o que fazer. Na sua língua. Grátis.",
    cardRiskDesc: "Veja o perigo perto da sua casa, conforme a idade do seu filho.",
    cardHealthDesc: "Diga-nos o que se passa — fale ou escreva na sua língua.",
    cardPhotoDesc: "Fotografe uma erupção, ferida, cheia ou fumo. Analisamos e dizemos o que fazer.",
    cardMapDesc: "Veja onde o perigo para as crianças é alto no mundo.",
    open: "Abrir",
    statChildren: "Crianças expostas a 3+ riscos climáticos",
    statStudents: "Alunos com aulas interrompidas em 2024",
    statDisplaced: "Crianças deslocadas por dia pelo clima",
    statCountries: "Países · 55 línguas disponíveis",
    whyTitle: "Porque criámos isto",
    storiesTitle: "Emergências reais",
    storiesSub: "Como as famílias usam o ClimaGuard quando mais importa",
    countriesTitle: "Feito para as crianças mais vulneráveis do mundo",
    countriesSub: "Todos os países de alto risco da UNICEF, em língua local",
    moreCountries: "+51 outros países",
    ctaTitle: "Comece a proteger o seu filho agora",
    ctaSub: "Escolha o seu país e a idade da criança — receba uma resposta e um plano na sua língua.",
    chipNoAccount: "Sem conta",
    chipFree: "100% grátis",
    chipLanguages: "55 línguas",
    notMedical: "Não substitui o conselho médico.",
    language: "Língua",
    country: "País",
    childAge: "Idade da criança",
    checkNow: "Verificar agora",
    checking: "A verificar…",
    tapMicSpeak: "Toque no microfone e fale na sua língua",
    recording: "A ouvir… toque no microfone outra vez quando terminar",
    listen: "Ouvir",
    stop: "Parar",
    typeOrSpeak: "Escreva aqui, ou toque no microfone e fale",
    send: "Enviar",
    riskLow: "O seu filho está seguro agora.",
    riskMedium: "Tenha cuidado. Vigie o seu filho.",
    riskHigh: "Perigo. Mantenha o seu filho dentro de casa, em segurança.",
    riskCritical: "MUITO PERIGOSO! Procure ajuda agora.",
    heatLabel: "Calor", heatDanger: "Está calor demais para as crianças. Refresque-as e dê água.", heatOk: "O calor está bem agora.",
    sunLabel: "Sol", sunDanger: "O sol está muito forte. Mantenha as crianças à sombra.", sunOk: "O sol está bem agora.",
    airLabel: "Ar", airDanger: "O ar está mau. Mantenha as crianças dentro de casa.", airOk: "O ar está bom agora.",
    rainLabel: "Chuva", rainDanger: "Chuva forte. A água pode subir. Vá para um lugar alto e seguro.", rainOk: "A chuva está bem agora.",
  },
  sw: {
    isMyChildInDanger: "Je, mtoto wangu yuko hatarini?",
    myChildIsSick: "Mtoto wangu ni mgonjwa",
    sendAPhoto: "Tuma picha",
    helpWithoutInternet: "Msaada bila intaneti",
    worldMap: "Ramani ya dunia",
    myChildren: "Watoto wangu",
    about: "Kuhusu",
    emergencyNow: "DHARURA — nisaidie sasa",
    emergencyNumbers: "Namba za dharura",
    tapToCall: "Gusa namba ili kupiga simu",
    worksOffline: "Inafanya kazi bila intaneti",
    callNow: "Piga simu sasa",
    tap: "GUSA",
    heroTitle: "Kulinda watoto dhidi ya hatari za hali ya hewa",
    heroSub: "Mafuriko, joto kali, dhoruba, hewa chafu — angalia kama mtoto wako yuko salama na cha kufanya. Kwa lugha yako. Bure.",
    cardRiskDesc: "Ona hatari karibu na nyumbani kwako, kulingana na umri wa mtoto.",
    cardHealthDesc: "Tuambie shida ni nini — ongea au andika kwa lugha yako.",
    cardPhotoDesc: "Piga picha ya vipele, jeraha, mafuriko au moshi. Tunaangalia na kukuambia cha kufanya.",
    cardMapDesc: "Ona wapi hatari kwa watoto iko juu duniani.",
    open: "Fungua",
    statChildren: "Watoto wanaokabili hatari 3+ za hali ya hewa",
    statStudents: "Wanafunzi walioathirika masomo 2024",
    statDisplaced: "Watoto wanaohama kila siku kwa sababu ya hali ya hewa",
    statCountries: "Nchi · lugha 55 zinapatikana",
    whyTitle: "Kwa nini tulitengeneza hii",
    storiesTitle: "Dharura za kweli",
    storiesSub: "Jinsi familia zinavyotumia ClimaGuard wakati wa shida",
    countriesTitle: "Imetengenezwa kwa watoto walio hatarini zaidi duniani",
    countriesSub: "Nchi zote za hatari kubwa za UNICEF, kwa lugha za wenyeji",
    moreCountries: "+ nchi nyingine 51",
    ctaTitle: "Anza kumlinda mtoto wako sasa",
    ctaSub: "Chagua nchi yako na umri wa mtoto — pata jibu na mpango kwa lugha yako.",
    chipNoAccount: "Hakuna akaunti",
    chipFree: "Bure kabisa",
    chipLanguages: "Lugha 55",
    notMedical: "Si mbadala wa ushauri wa daktari.",
    language: "Lugha",
    country: "Nchi",
    childAge: "Umri wa mtoto",
    checkNow: "Angalia sasa",
    checking: "Inaangalia…",
    tapMicSpeak: "Gusa kipaza sauti, ongea kwa lugha yako",
    recording: "Tunasikiliza… gusa kipaza sauti tena ukimaliza",
    listen: "Sikiliza",
    stop: "Simamisha",
    typeOrSpeak: "Andika hapa, au gusa kipaza sauti uongee",
    send: "Tuma",
    riskLow: "Mtoto wako yuko salama sasa.",
    riskMedium: "Kuwa makini. Mwangalie mtoto wako.",
    riskHigh: "Hatari. Mweke mtoto ndani, salama.",
    riskCritical: "HATARI KUBWA! Tafuta msaada sasa.",
    heatLabel: "Joto", heatDanger: "Kuna joto kali sana kwa watoto. Wapoze, wape maji.", heatOk: "Joto liko sawa sasa.",
    sunLabel: "Jua", sunDanger: "Jua ni kali sana. Waweke watoto kivulini.", sunOk: "Jua liko sawa sasa.",
    airLabel: "Hewa", airDanger: "Hewa ni chafu. Waweke watoto ndani.", airOk: "Hewa iko safi sasa.",
    rainLabel: "Mvua", rainDanger: "Mvua kubwa. Maji yanaweza kupanda. Nenda mahali pa juu na salama.", rainOk: "Mvua iko sawa sasa.",
  },
  ha: {
    isMyChildInDanger: "Shin ɗana yana cikin haɗari?",
    myChildIsSick: "Ɗana yana rashin lafiya",
    sendAPhoto: "Aika hoto",
    helpWithoutInternet: "Taimako ba tare da intanet ba",
    worldMap: "Taswirar duniya",
    myChildren: "Yarana",
    about: "Game da mu",
    emergencyNow: "GAGGAWA — a taimake ni yanzu",
    emergencyNumbers: "Lambobin gaggawa",
    tapToCall: "Danna lamba don kira",
    worksOffline: "Yana aiki ba tare da intanet ba",
    callNow: "Kira yanzu",
    tap: "DANNA",
    heroTitle: "Kare yara daga haɗarin yanayi",
    heroSub: "Ambaliya, zafi, hadari, gurɓataccen iska — duba ko yaronka yana lafiya da abin da za ka yi. Da yarenka. Kyauta.",
    cardRiskDesc: "Duba haɗarin da ke kusa da gidanka, bisa shekarun yaronka.",
    cardHealthDesc: "Faɗa mana me ke damun yaro — yi magana ko rubuta da yarenka.",
    cardPhotoDesc: "Ɗauki hoton kurji, rauni, ambaliya ko hayaƙi. Za mu duba mu gaya maka abin da za ka yi.",
    cardMapDesc: "Duba inda haɗari ga yara ya yi yawa a duniya.",
    open: "Buɗe",
    statChildren: "Yara da ke fuskantar haɗarin yanayi 3+",
    statStudents: "Ɗalibai da karatunsu ya tsinke a 2024",
    statDisplaced: "Yara da ke rasa gida kullum saboda yanayi",
    statCountries: "Ƙasashe · harsuna 55",
    whyTitle: "Dalilin da ya sa muka gina wannan",
    storiesTitle: "Al'amuran gaggawa na gaske",
    storiesSub: "Yadda iyalai ke amfani da ClimaGuard a lokacin wahala",
    countriesTitle: "An gina don yara mafi rauni a duniya",
    countriesSub: "Duk ƙasashen UNICEF masu haɗari, da harsunan gida",
    moreCountries: "+ wasu ƙasashe 51",
    ctaTitle: "Fara kare yaronka yanzu",
    ctaSub: "Zaɓi ƙasarka da shekarun yaro — samu amsa da shiri da yarenka.",
    chipNoAccount: "Ba a buƙatar asusu",
    chipFree: "Kyauta 100%",
    chipLanguages: "Harsuna 55",
    notMedical: "Ba madadin shawarar likita ba ne.",
    language: "Harshe",
    country: "Ƙasa",
    childAge: "Shekarun yaro",
    checkNow: "Duba yanzu",
    checking: "Ana dubawa…",
    tapMicSpeak: "Danna makirufo, yi magana da yarenka",
    recording: "Muna saurare… danna makirufo kuma idan ka gama",
    listen: "Saurara",
    stop: "Tsaya",
    typeOrSpeak: "Rubuta a nan, ko danna makirufo ka yi magana",
    send: "Aika",
    riskLow: "Yaronka yana lafiya yanzu.",
    riskMedium: "Yi hankali. Kula da yaronka.",
    riskHigh: "Haɗari. Ajiye yaronka a cikin gida lafiya.",
    riskCritical: "HAƊARI SOSAI! Nemi taimako yanzu.",
    heatLabel: "Zafi", heatDanger: "Zafi ya yi yawa ga yara. Sanyaya su, ba su ruwa.", heatOk: "Zafi ba matsala yanzu.",
    sunLabel: "Rana", sunDanger: "Rana tana da ƙarfi sosai. Ajiye yara a inuwa.", sunOk: "Rana ba matsala yanzu.",
    airLabel: "Iska", airDanger: "Iska ba ta da kyau. Ajiye yara a cikin gida.", airOk: "Iska tana da kyau yanzu.",
    rainLabel: "Ruwan sama", rainDanger: "Ruwan sama mai ƙarfi. Ruwa na iya hauhawa. Je wuri mai tsayi da aminci.", rainOk: "Ruwan sama ba matsala yanzu.",
  },
  am: {
    isMyChildInDanger: "ልጄ አደጋ ላይ ነው?",
    myChildIsSick: "ልጄ ታሟል",
    sendAPhoto: "ፎቶ ላክ",
    helpWithoutInternet: "ያለ ኢንተርኔት እርዳታ",
    worldMap: "የዓለም ካርታ",
    myChildren: "ልጆቼ",
    about: "ስለ እኛ",
    emergencyNow: "አደጋ — አሁን እርዱኝ",
    emergencyNumbers: "የአደጋ ጊዜ ስልኮች",
    tapToCall: "ለመደወል ቁጥሩን ይንኩ",
    worksOffline: "ያለ ኢንተርኔት ይሰራል",
    callNow: "አሁን ይደውሉ",
    tap: "ይንኩ",
    heroTitle: "ልጆችን ከአየር ንብረት አደጋ መጠበቅ",
    heroSub: "ጎርፍ፣ ሙቀት፣ አውሎ ነፋስ፣ መጥፎ አየር — ልጅዎ ደህና መሆኑን እና ምን ማድረግ እንዳለብዎ ይመልከቱ። በቋንቋዎ። በነጻ።",
    cardRiskDesc: "በአካባቢዎ ለልጅዎ ዕድሜ ያለውን አደጋ ይመልከቱ።",
    cardHealthDesc: "ችግሩ ምን እንደሆነ ይንገሩን — በቋንቋዎ ይናገሩ ወይም ይጻፉ።",
    cardPhotoDesc: "ሽፍታ፣ ቁስል፣ ጎርፍ ወይም ጭስ ፎቶ ያንሱ። አይተን ምን ማድረግ እንዳለብዎ እንነግርዎታለን።",
    cardMapDesc: "በዓለም ላይ ለልጆች አደጋ የት እንደሚበዛ ይመልከቱ።",
    open: "ክፈት",
    statChildren: "3+ የአየር ንብረት አደጋ የሚጋፈጡ ልጆች",
    statStudents: "በ2024 ትምህርታቸው የተስተጓጎለ ተማሪዎች",
    statDisplaced: "በአየር ንብረት ምክንያት በየቀኑ የሚፈናቀሉ ልጆች",
    statCountries: "አገሮች · በ55 ቋንቋዎች ድጋፍ",
    whyTitle: "ይህን ለምን ሠራን",
    storiesTitle: "እውነተኛ የአደጋ ሁኔታዎች",
    storiesSub: "ቤተሰቦች በችግር ጊዜ ClimaGuard እንዴት እንደሚጠቀሙ",
    countriesTitle: "ለዓለም በጣም ተጋላጭ ልጆች የተሠራ",
    countriesSub: "ሁሉም የUNICEF ከፍተኛ አደጋ አገሮች፣ በአካባቢ ቋንቋ",
    moreCountries: "+51 ተጨማሪ አገሮች",
    ctaTitle: "ልጅዎን መጠበቅ አሁን ይጀምሩ",
    ctaSub: "አገርዎን እና የልጅዎን ዕድሜ ይምረጡ — በቋንቋዎ መልስ እና እቅድ ያግኙ።",
    chipNoAccount: "መለያ አያስፈልግም",
    chipFree: "ሙሉ በሙሉ ነጻ",
    chipLanguages: "55 ቋንቋዎች",
    notMedical: "የሐኪም ምክር ምትክ አይደለም።",
    language: "ቋንቋ",
    country: "አገር",
    childAge: "የልጅ ዕድሜ",
    checkNow: "አሁን ይመልከቱ",
    checking: "በመፈተሽ ላይ…",
    tapMicSpeak: "ማይክሩን ይንኩ፣ በቋንቋዎ ይናገሩ",
    recording: "እያዳመጥን ነው… ሲጨርሱ ማይክሩን እንደገና ይንኩ",
    listen: "ያዳምጡ",
    stop: "አቁም",
    typeOrSpeak: "እዚህ ይጻፉ፣ ወይም ማይክሩን ነክተው ይናገሩ",
    send: "ላክ",
    riskLow: "ልጅዎ አሁን ደህና ነው።",
    riskMedium: "ይጠንቀቁ። ልጅዎን ይከታተሉ።",
    riskHigh: "አደጋ። ልጅዎን በቤት ውስጥ ደህንነቱ በተጠበቀ ሁኔታ ያቆዩ።",
    riskCritical: "በጣም አደገኛ! አሁን እርዳታ ይፈልጉ።",
    heatLabel: "ሙቀት", heatDanger: "ለልጆች በጣም ሞቃት ነው። ያቀዘቅዙ፣ ውሃ ይስጡ።", heatOk: "ሙቀቱ አሁን ችግር የለውም።",
    sunLabel: "ፀሐይ", sunDanger: "ፀሐይ በጣም ኃይለኛ ነው። ልጆችን በጥላ ውስጥ ያቆዩ።", sunOk: "ፀሐይ አሁን ችግር የለውም።",
    airLabel: "አየር", airDanger: "አየሩ መጥፎ ነው። ልጆችን በቤት ውስጥ ያቆዩ።", airOk: "አየሩ አሁን ጥሩ ነው።",
    rainLabel: "ዝናብ", rainDanger: "ኃይለኛ ዝናብ። ውሃ ሊጨምር ይችላል። ወደ ከፍ ያለ ደህና ቦታ ይሂዱ።", rainOk: "ዝናቡ አሁን ችግር የለውም።",
  },
  so: {
    isMyChildInDanger: "Ilmahaygu ma khatar buu ku jiraa?",
    myChildIsSick: "Ilmahaygu wuu xanuunsanayaa",
    sendAPhoto: "Sawir dir",
    helpWithoutInternet: "Caawimaad internet la'aan",
    worldMap: "Khariidadda adduunka",
    myChildren: "Carruurtayda",
    about: "Nagu saabsan",
    emergencyNow: "DEG DEG — hadda i caawiya",
    emergencyNumbers: "Lambarrada gurmadka",
    tapToCall: "Taabo lambarka si aad u wacdo",
    worksOffline: "Wuxuu shaqeeyaa internet la'aan",
    callNow: "Hadda wac",
    tap: "RIIX",
    heroTitle: "Ka ilaalinta carruurta khatarta cimilada",
    heroSub: "Daadad, kulayl, duufaanno, hawo xun — eeg in ilmahaagu nabad yahay iyo waxa la sameeyo. Luqaddaada. Bilaash.",
    cardRiskDesc: "Arag khatarta u dhow gurigaaga, sida da'da ilmahaaga.",
    cardHealthDesc: "Noo sheeg waxa dhibaya — ku hadal ama ku qor luqaddaada.",
    cardPhotoDesc: "Sawir finan, nabar, daad ama qiiq. Waan eegnaa oo kuu sheegnaa waxa la sameeyo.",
    cardMapDesc: "Arag meesha khatarta carruurtu ku badan tahay adduunka.",
    open: "Fur",
    statChildren: "Carruur la kulanta 3+ khatarood oo cimilo",
    statStudents: "Arday waxbarashadoodu carqaladaysantay 2024",
    statDisplaced: "Carruur maalin kasta barakacda cimilada darteed",
    statCountries: "Dalal · 55 luqadood",
    whyTitle: "Sababta aan u dhisnay",
    storiesTitle: "Xaalado degdeg ah oo dhab ah",
    storiesSub: "Sida qoysasku u isticmaalaan ClimaGuard wakhtiga dhibka",
    countriesTitle: "Loo dhisay carruurta ugu nugul adduunka",
    countriesSub: "Dhammaan dalalka halista sare ee UNICEF, luqadaha maxalliga ah",
    moreCountries: "+51 dal oo kale",
    ctaTitle: "Hadda bilow ilaalinta ilmahaaga",
    ctaSub: "Dooro dalkaaga iyo da'da ilmaha — hel jawaab iyo qorshe luqaddaada.",
    chipNoAccount: "Akoon looma baahna",
    chipFree: "Bilaash buuxa",
    chipLanguages: "55 luqadood",
    notMedical: "Kuma beddelo talada dhakhtarka.",
    language: "Luqadda",
    country: "Dalka",
    childAge: "Da'da ilmaha",
    checkNow: "Hadda hubi",
    checking: "Waa la hubinayaa…",
    tapMicSpeak: "Taabo makarafoonka, kuna hadal luqaddaada",
    recording: "Waan dhegeysanaynaa… mar kale taabo makarafoonka markaad dhammayso",
    listen: "Dhegayso",
    stop: "Jooji",
    typeOrSpeak: "Halkan wax ku qor, ama taabo makarafoonka oo hadal",
    send: "Dir",
    riskLow: "Ilmahaagu hadda waa nabad.",
    riskMedium: "Ka taxaddar. Ilaali ilmahaaga.",
    riskHigh: "Khatar. Ilmahaaga gudaha ku hay si nabad ah.",
    riskCritical: "AAD U KHATAR AH! Hadda caawimaad raadso.",
    heatLabel: "Kulayl", heatDanger: "Aad bay ugu kulushahay carruurta. Qabooji, biyo sii.", heatOk: "Kulaylku hadda waa caadi.",
    sunLabel: "Qorrax", sunDanger: "Qorraxdu aad bay u daran tahay. Carruurta hooska ku hay.", sunOk: "Qorraxdu hadda waa caadi.",
    airLabel: "Hawo", airDanger: "Hawadu waa xun tahay. Carruurta gudaha ku hay.", airOk: "Hawadu hadda waa fiican tahay.",
    rainLabel: "Roob", rainDanger: "Roob weyn. Biyuhu way kori karaan. Aad meel sare oo nabad ah.", rainOk: "Roobku hadda waa caadi.",
  },
  fil: {
    isMyChildInDanger: "Nasa panganib ba ang anak ko?",
    myChildIsSick: "May sakit ang anak ko",
    sendAPhoto: "Magpadala ng litrato",
    helpWithoutInternet: "Tulong kahit walang internet",
    worldMap: "Mapa ng mundo",
    myChildren: "Mga anak ko",
    about: "Tungkol",
    emergencyNow: "EMERGENCY — tulungan ninyo ako ngayon",
    emergencyNumbers: "Mga emergency na numero",
    tapToCall: "Pindutin ang numero para tumawag",
    worksOffline: "Gumagana kahit walang internet",
    callNow: "Tumawag ngayon",
    tap: "PINDUTIN",
    heroTitle: "Pagprotekta sa mga bata mula sa panganib ng panahon",
    heroSub: "Baha, init, bagyo, maruming hangin — tingnan kung ligtas ang inyong anak at ano ang gagawin. Sa inyong wika. Libre.",
    cardRiskDesc: "Tingnan ang panganib malapit sa inyong bahay, ayon sa edad ng anak.",
    cardHealthDesc: "Sabihin kung ano ang problema — magsalita o magsulat sa inyong wika.",
    cardPhotoDesc: "Kunan ng litrato ang pantal, sugat, baha o usok. Titingnan namin at sasabihin kung ano ang gagawin.",
    cardMapDesc: "Tingnan kung saan mataas ang panganib sa mga bata sa mundo.",
    open: "Buksan",
    statChildren: "Mga batang nakararanas ng 3+ panganib sa klima",
    statStudents: "Mga mag-aaral na naantala ang pag-aaral noong 2024",
    statDisplaced: "Mga batang napapalayas araw-araw dahil sa klima",
    statCountries: "Mga bansa · 55 wika",
    whyTitle: "Bakit namin ito ginawa",
    storiesTitle: "Tunay na mga emergency",
    storiesSub: "Paano ginagamit ng mga pamilya ang ClimaGuard sa oras ng pangangailangan",
    countriesTitle: "Ginawa para sa pinaka-nanganganib na mga bata sa mundo",
    countriesSub: "Lahat ng high-risk na bansa ng UNICEF, sa lokal na wika",
    moreCountries: "+51 pang bansa",
    ctaTitle: "Simulan nang protektahan ang inyong anak",
    ctaSub: "Piliin ang bansa at edad ng anak — makakuha ng sagot at plano sa inyong wika.",
    chipNoAccount: "Hindi kailangan ng account",
    chipFree: "100% libre",
    chipLanguages: "55 wika",
    notMedical: "Hindi kapalit ng payo ng doktor.",
    language: "Wika",
    country: "Bansa",
    childAge: "Edad ng bata",
    checkNow: "Tingnan ngayon",
    checking: "Tinitingnan…",
    tapMicSpeak: "Pindutin ang mikropono at magsalita sa inyong wika",
    recording: "Nakikinig… pindutin ulit ang mikropono kapag tapos na",
    listen: "Pakinggan",
    stop: "Ihinto",
    typeOrSpeak: "Magsulat dito, o pindutin ang mikropono at magsalita",
    send: "Ipadala",
    riskLow: "Ligtas ang inyong anak ngayon.",
    riskMedium: "Mag-ingat. Bantayan ang inyong anak.",
    riskHigh: "Panganib. Panatilihin ang bata sa loob ng bahay, ligtas.",
    riskCritical: "NAPAKADELIKADO! Humingi ng tulong ngayon.",
    heatLabel: "Init", heatDanger: "Sobrang init para sa mga bata. Palamigin sila, painumin ng tubig.", heatOk: "Ayos lang ang init ngayon.",
    sunLabel: "Araw", sunDanger: "Napakatindi ng araw. Ilagay ang mga bata sa lilim.", sunOk: "Ayos lang ang araw ngayon.",
    airLabel: "Hangin", airDanger: "Marumi ang hangin. Panatilihin ang mga bata sa loob.", airOk: "Malinis ang hangin ngayon.",
    rainLabel: "Ulan", rainDanger: "Malakas na ulan. Maaaring tumaas ang tubig. Pumunta sa mataas at ligtas na lugar.", rainOk: "Ayos lang ang ulan ngayon.",
  },
  id: {
    isMyChildInDanger: "Apakah anak saya dalam bahaya?",
    myChildIsSick: "Anak saya sakit",
    sendAPhoto: "Kirim foto",
    helpWithoutInternet: "Bantuan tanpa internet",
    worldMap: "Peta dunia",
    myChildren: "Anak-anak saya",
    about: "Tentang",
    emergencyNow: "DARURAT — tolong saya sekarang",
    emergencyNumbers: "Nomor darurat",
    tapToCall: "Ketuk nomor untuk menelepon",
    worksOffline: "Bekerja tanpa internet",
    callNow: "Telepon sekarang",
    tap: "TEKAN",
    heroTitle: "Melindungi anak dari bahaya cuaca",
    heroSub: "Banjir, panas, badai, udara kotor — lihat apakah anak Anda aman dan apa yang harus dilakukan. Dalam bahasa Anda. Gratis.",
    cardRiskDesc: "Lihat bahaya di dekat rumah Anda, sesuai umur anak.",
    cardHealthDesc: "Ceritakan apa masalahnya — bicara atau tulis dalam bahasa Anda.",
    cardPhotoDesc: "Foto ruam, luka, banjir, atau asap. Kami periksa dan beri tahu apa yang harus dilakukan.",
    cardMapDesc: "Lihat di mana bahaya bagi anak-anak tinggi di dunia.",
    open: "Buka",
    statChildren: "Anak yang menghadapi 3+ bahaya iklim",
    statStudents: "Pelajar yang sekolahnya terganggu pada 2024",
    statDisplaced: "Anak mengungsi setiap hari karena iklim",
    statCountries: "Negara · 55 bahasa tersedia",
    whyTitle: "Mengapa kami membuat ini",
    storiesTitle: "Keadaan darurat nyata",
    storiesSub: "Bagaimana keluarga memakai ClimaGuard saat dibutuhkan",
    countriesTitle: "Dibuat untuk anak-anak paling rentan di dunia",
    countriesSub: "Semua negara berisiko tinggi UNICEF, dalam bahasa lokal",
    moreCountries: "+51 negara lainnya",
    ctaTitle: "Mulai lindungi anak Anda sekarang",
    ctaSub: "Pilih negara dan umur anak — dapatkan jawaban dan rencana dalam bahasa Anda.",
    chipNoAccount: "Tanpa akun",
    chipFree: "100% gratis",
    chipLanguages: "55 bahasa",
    notMedical: "Bukan pengganti saran dokter.",
    language: "Bahasa",
    country: "Negara",
    childAge: "Umur anak",
    checkNow: "Periksa sekarang",
    checking: "Memeriksa…",
    tapMicSpeak: "Ketuk mikrofon, bicaralah dalam bahasa Anda",
    recording: "Mendengarkan… ketuk mikrofon lagi jika sudah selesai",
    listen: "Dengarkan",
    stop: "Berhenti",
    typeOrSpeak: "Tulis di sini, atau ketuk mikrofon dan bicara",
    send: "Kirim",
    riskLow: "Anak Anda aman sekarang.",
    riskMedium: "Hati-hati. Awasi anak Anda.",
    riskHigh: "Bahaya. Jaga anak tetap di dalam rumah, aman.",
    riskCritical: "SANGAT BERBAHAYA! Cari bantuan sekarang.",
    heatLabel: "Panas", heatDanger: "Terlalu panas untuk anak-anak. Dinginkan mereka, beri air minum.", heatOk: "Panas tidak berbahaya sekarang.",
    sunLabel: "Matahari", sunDanger: "Matahari sangat terik. Jaga anak di tempat teduh.", sunOk: "Matahari tidak berbahaya sekarang.",
    airLabel: "Udara", airDanger: "Udara buruk. Jaga anak tetap di dalam rumah.", airOk: "Udara baik sekarang.",
    rainLabel: "Hujan", rainDanger: "Hujan deras. Air bisa naik. Pergilah ke tempat tinggi yang aman.", rainOk: "Hujan tidak berbahaya sekarang.",
  },
  ps: {
    isMyChildInDanger: "ایا زما ماشوم په خطر کې دی؟",
    myChildIsSick: "زما ماشوم ناروغ دی",
    sendAPhoto: "عکس واستوئ",
    helpWithoutInternet: "له انټرنېټ پرته مرسته",
    worldMap: "د نړۍ نقشه",
    myChildren: "زما ماشومان",
    about: "زموږ په اړه",
    emergencyNow: "بيړنی حالت — همدا اوس مرسته وکړئ",
    emergencyNumbers: "بيړني شمېرې",
    tapToCall: "د زنګ وهلو لپاره شمېره کېکاږئ",
    worksOffline: "له انټرنېټ پرته هم کار کوي",
    callNow: "همدا اوس زنګ ووهئ",
    tap: "کېکاږئ",
    heroTitle: "د هوا له خطرونو څخه د ماشومانو ساتنه",
    heroSub: "سېلابونه، ګرمي، طوفانونه، ککړه هوا — وګورئ چې ماشوم مو خوندي دی که نه او څه وکړئ. ستاسو په ژبه. وړيا.",
    cardRiskDesc: "د خپل کور شاوخوا خطر د ماشوم د عمر له مخې وګورئ.",
    cardHealthDesc: "راته ووايئ ستونزه څه ده — په خپله ژبه خبرې وکړئ يا وليکئ.",
    cardPhotoDesc: "د دانو، زخم، سېلاب يا لوګي عکس واخلئ. موږ يې ګورو او درته وايو چې څه وکړئ.",
    cardMapDesc: "وګورئ چې په نړۍ کې ماشومانو ته خطر چېرته زيات دی.",
    open: "پرانيزئ",
    statChildren: "هغه ماشومان چې له ۳+ اقليمي خطرونو سره مخ دي",
    statStudents: "هغه زده کوونکي چې په ۲۰۲۴ کې يې زده کړې ګډوډې شوې",
    statDisplaced: "هغه ماشومان چې هره ورځ د اقليم له امله بې ځايه کيږي",
    statCountries: "هېوادونه · ۵۵ ژبې",
    whyTitle: "ولې مو دا جوړ کړ",
    storiesTitle: "ريښتيني بيړني پېښې",
    storiesSub: "کورنۍ په سختو شېبو کې ClimaGuard څنګه کاروي",
    countriesTitle: "د نړۍ د خورا زيانمنونکو ماشومانو لپاره جوړ شوی",
    countriesSub: "د UNICEF ټول لوړ خطر هېوادونه، په سيمه ييزو ژبو",
    moreCountries: "+۵۱ نور هېوادونه",
    ctaTitle: "همدا اوس د خپل ماشوم ساتنه پيل کړئ",
    ctaSub: "خپل هېواد او د ماشوم عمر وټاکئ — په خپله ژبه ځواب او پلان ترلاسه کړئ.",
    chipNoAccount: "حساب ته اړتيا نشته",
    chipFree: "بشپړ وړيا",
    chipLanguages: "۵۵ ژبې",
    notMedical: "د ډاکټر د مشورې بديل نه دی.",
    language: "ژبه",
    country: "هېواد",
    childAge: "د ماشوم عمر",
    checkNow: "همدا اوس وګورئ",
    checking: "کتل کيږي…",
    tapMicSpeak: "مايکروفون کېکاږئ او په خپله ژبه خبرې وکړئ",
    recording: "اورو… چې خبرې مو پای ته ورسېدې بيا مايکروفون کېکاږئ",
    listen: "واورئ",
    stop: "ودروئ",
    typeOrSpeak: "دلته وليکئ، يا مايکروفون کېکاږئ او خبرې وکړئ",
    send: "واستوئ",
    riskLow: "ستاسو ماشوم اوس خوندي دی.",
    riskMedium: "پام کوئ. خپل ماشوم ته پام کوئ.",
    riskHigh: "خطر. ماشوم په کور کې خوندي وساتئ.",
    riskCritical: "ډېر خطرناک! همدا اوس مرسته وغواړئ.",
    heatLabel: "ګرمي", heatDanger: "د ماشومانو لپاره ډېره ګرمي ده. سړه يې کړئ، اوبه ورکړئ.", heatOk: "ګرمي اوس ستونزه نه ده.",
    sunLabel: "لمر", sunDanger: "لمر ډېر تېز دی. ماشومان په سيوري کې وساتئ.", sunOk: "لمر اوس ستونزه نه ده.",
    airLabel: "هوا", airDanger: "هوا خرابه ده. ماشومان په کور کې وساتئ.", airOk: "هوا اوس ښه ده.",
    rainLabel: "باران", rainDanger: "سخت باران. اوبه لوړېدای شي. لوړ او خوندي ځای ته لاړ شئ.", rainOk: "باران اوس ستونزه نه ده.",
  },
  my: {
    isMyChildInDanger: "ကျွန်ုပ်ကလေး အန္တရာယ်ရှိနေသလား?",
    myChildIsSick: "ကျွန်ုပ်ကလေး နေမကောင်းပါ",
    sendAPhoto: "ဓာတ်ပုံပို့ပါ",
    helpWithoutInternet: "အင်တာနက်မလိုဘဲ အကူအညီ",
    worldMap: "ကမ္ဘာ့မြေပုံ",
    myChildren: "ကျွန်ုပ်၏ကလေးများ",
    about: "အကြောင်း",
    emergencyNow: "အရေးပေါ် — အခုချက်ချင်း ကူညီပါ",
    emergencyNumbers: "အရေးပေါ်ဖုန်းနံပါတ်များ",
    tapToCall: "ခေါ်ဆိုရန် နံပါတ်ကိုနှိပ်ပါ",
    worksOffline: "အင်တာနက်မရှိလည်း အလုပ်လုပ်သည်",
    callNow: "အခုဖုန်းခေါ်ပါ",
    tap: "နှိပ်ပါ",
    heroTitle: "ရာသီဥတုအန္တရာယ်မှ ကလေးများကို ကာကွယ်ခြင်း",
    heroSub: "ရေကြီးခြင်း၊ အပူ၊ မုန်တိုင်း၊ လေထုညစ်ညမ်းမှု — ကလေးဘေးကင်းမကင်း နှင့် ဘာလုပ်ရမည်ကို ကြည့်ပါ။ သင့်ဘာသာစကားဖြင့်။ အခမဲ့။",
    cardRiskDesc: "သင့်အိမ်အနီးရှိ အန္တရာယ်ကို ကလေးအသက်အလိုက် ကြည့်ပါ။",
    cardHealthDesc: "ဘာဖြစ်နေသည်ကို ပြောပြပါ — သင့်ဘာသာစကားဖြင့် ပြောပါ သို့မဟုတ် ရေးပါ။",
    cardPhotoDesc: "အဖုအပိမ့်၊ ဒဏ်ရာ၊ ရေကြီးမှု သို့မဟုတ် မီးခိုးကို ဓာတ်ပုံရိုက်ပါ။ ကြည့်ပြီး ဘာလုပ်ရမည်ကို ပြောပါမည်။",
    cardMapDesc: "ကမ္ဘာပေါ်တွင် ကလေးများအတွက် အန္တရာယ်များသောနေရာများကို ကြည့်ပါ။",
    open: "ဖွင့်ရန်",
    statChildren: "ရာသီဥတုအန္တရာယ် ၃+ ရင်ဆိုင်နေရသော ကလေးများ",
    statStudents: "၂၀၂၄ တွင် ပညာရေးထိခိုက်ခဲ့သော ကျောင်းသားများ",
    statDisplaced: "ရာသီဥတုကြောင့် နေ့စဉ်နေရပ်စွန့်ခွာရသော ကလေးများ",
    statCountries: "နိုင်ငံများ · ဘာသာစကား ၅၅ မျိုး",
    whyTitle: "ဘာကြောင့် ဤအက်ပ်ကို တည်ဆောက်ခဲ့သနည်း",
    storiesTitle: "အမှန်တကယ် အရေးပေါ်အခြေအနေများ",
    storiesSub: "အခက်အခဲအချိန်တွင် မိသားစုများ ClimaGuard ကို မည်သို့အသုံးပြုကြသည်",
    countriesTitle: "ကမ္ဘာ့အထိခိုက်လွယ်ဆုံး ကလေးများအတွက် တည်ဆောက်ထားသည်",
    countriesSub: "UNICEF ၏ အန္တရာယ်မြင့်နိုင်ငံအားလုံး၊ ဒေသဘာသာစကားဖြင့်",
    moreCountries: "+ နောက်ထပ် နိုင်ငံ ၅၁ နိုင်ငံ",
    ctaTitle: "သင့်ကလေးကို ယခုပင် စတင်ကာကွယ်ပါ",
    ctaSub: "နိုင်ငံနှင့် ကလေးအသက်ကို ရွေးပါ — သင့်ဘာသာစကားဖြင့် အဖြေနှင့် အစီအစဉ်ရယူပါ။",
    chipNoAccount: "အကောင့်မလိုပါ",
    chipFree: "လုံးဝအခမဲ့",
    chipLanguages: "ဘာသာစကား ၅၅ မျိုး",
    notMedical: "ဆရာဝန်၏အကြံဉာဏ် အစားထိုးမဟုတ်ပါ။",
    language: "ဘာသာစကား",
    country: "နိုင်ငံ",
    childAge: "ကလေးအသက်",
    checkNow: "အခုစစ်ကြည့်ပါ",
    checking: "စစ်ဆေးနေသည်…",
    tapMicSpeak: "မိုက်ကိုနှိပ်ပြီး သင့်ဘာသာစကားဖြင့် ပြောပါ",
    recording: "နားထောင်နေသည်… ပြီးလျှင် မိုက်ကို ထပ်နှိပ်ပါ",
    listen: "နားထောင်ရန်",
    stop: "ရပ်ရန်",
    typeOrSpeak: "ဤနေရာတွင်ရေးပါ သို့မဟုတ် မိုက်နှိပ်၍ပြောပါ",
    send: "ပို့ရန်",
    riskLow: "သင့်ကလေး ယခုဘေးကင်းပါသည်။",
    riskMedium: "သတိထားပါ။ ကလေးကို စောင့်ကြည့်ပါ။",
    riskHigh: "အန္တရာယ်ရှိသည်။ ကလေးကို အိမ်ထဲတွင် ဘေးကင်းစွာထားပါ။",
    riskCritical: "အလွန်အန္တရာယ်ကြီးသည်! အခုချက်ချင်း အကူအညီရယူပါ။",
    heatLabel: "အပူ", heatDanger: "ကလေးများအတွက် အလွန်ပူသည်။ အအေးပေးပြီး ရေတိုက်ပါ။", heatOk: "အပူချိန် ယခုပြဿနာမရှိပါ။",
    sunLabel: "နေ", sunDanger: "နေရောင် အလွန်ပြင်းသည်။ ကလေးများကို အရိပ်တွင်ထားပါ။", sunOk: "နေရောင် ယခုပြဿနာမရှိပါ။",
    airLabel: "လေ", airDanger: "လေထုညစ်ညမ်းသည်။ ကလေးများကို အိမ်ထဲတွင်ထားပါ။", airOk: "လေထု ယခုကောင်းပါသည်။",
    rainLabel: "မိုး", rainDanger: "မိုးသည်းထန်သည်။ ရေမြင့်တက်နိုင်သည်။ မြင့်၍ဘေးကင်းသောနေရာသို့ သွားပါ။", rainOk: "မိုး ယခုပြဿနာမရှိပါ။",
  },
  km: {
    isMyChildInDanger: "តើកូនខ្ញុំមានគ្រោះថ្នាក់ទេ?",
    myChildIsSick: "កូនខ្ញុំឈឺ",
    sendAPhoto: "ផ្ញើរូបថត",
    helpWithoutInternet: "ជំនួយដោយគ្មានអ៊ីនធឺណិត",
    worldMap: "ផែនទីពិភពលោក",
    myChildren: "កូនៗរបស់ខ្ញុំ",
    about: "អំពី",
    emergencyNow: "បន្ទាន់ — ជួយខ្ញុំឥឡូវនេះ",
    emergencyNumbers: "លេខទូរស័ព្ទបន្ទាន់",
    tapToCall: "ចុចលេខដើម្បីហៅ",
    worksOffline: "ដំណើរការដោយគ្មានអ៊ីនធឺណិត",
    callNow: "ហៅឥឡូវនេះ",
    tap: "ចុច",
    heroTitle: "ការពារកុមារពីគ្រោះថ្នាក់អាកាសធាតុ",
    heroSub: "ទឹកជំនន់ កំដៅ ព្យុះ ខ្យល់អាក្រក់ — មើលថាកូនអ្នកមានសុវត្ថិភាពឬអត់ និងអ្វីដែលត្រូវធ្វើ។ ជាភាសារបស់អ្នក។ ឥតគិតថ្លៃ។",
    cardRiskDesc: "មើលគ្រោះថ្នាក់ក្បែរផ្ទះអ្នក តាមអាយុកូន។",
    cardHealthDesc: "ប្រាប់យើងថាមានបញ្ហាអ្វី — និយាយ ឬសរសេរជាភាសារបស់អ្នក។",
    cardPhotoDesc: "ថតរូបកន្ទួល របួស ទឹកជំនន់ ឬផ្សែង។ យើងមើលហើយប្រាប់អ្នកពីអ្វីដែលត្រូវធ្វើ។",
    cardMapDesc: "មើលកន្លែងដែលគ្រោះថ្នាក់ខ្ពស់សម្រាប់កុមារនៅលើពិភពលោក។",
    open: "បើក",
    statChildren: "កុមារប្រឈមនឹងគ្រោះថ្នាក់អាកាសធាតុ ៣+",
    statStudents: "សិស្សដែលការសិក្សារំខាននៅ ២០២៤",
    statDisplaced: "កុមារផ្លាស់ទីលំនៅរាល់ថ្ងៃដោយសារអាកាសធាតុ",
    statCountries: "ប្រទេស · ៥៥ ភាសា",
    whyTitle: "ហេតុអ្វីយើងបង្កើតវា",
    storiesTitle: "ស្ថានការណ៍បន្ទាន់ពិតៗ",
    storiesSub: "របៀបគ្រួសារប្រើ ClimaGuard ពេលមានអាសន្ន",
    countriesTitle: "បង្កើតសម្រាប់កុមារងាយរងគ្រោះបំផុតលើពិភពលោក",
    countriesSub: "គ្រប់ប្រទេសហានិភ័យខ្ពស់របស់ UNICEF ជាភាសាមូលដ្ឋាន",
    moreCountries: "+៥១ ប្រទេសទៀត",
    ctaTitle: "ចាប់ផ្តើមការពារកូនអ្នកឥឡូវនេះ",
    ctaSub: "ជ្រើសរើសប្រទេស និងអាយុកូន — ទទួលចម្លើយ និងផែនការជាភាសារបស់អ្នក។",
    chipNoAccount: "មិនត្រូវការគណនី",
    chipFree: "ឥតគិតថ្លៃទាំងស្រុង",
    chipLanguages: "៥៥ ភាសា",
    notMedical: "មិនមែនជាការជំនួសដំបូន្មានវេជ្ជបណ្ឌិតទេ។",
    language: "ភាសា",
    country: "ប្រទេស",
    childAge: "អាយុកូន",
    checkNow: "ពិនិត្យឥឡូវនេះ",
    checking: "កំពុងពិនិត្យ…",
    tapMicSpeak: "ចុចមីក្រូហ្វូន ហើយនិយាយជាភាសារបស់អ្នក",
    recording: "កំពុងស្តាប់… ចុចមីក្រូហ្វូនម្តងទៀតពេលនិយាយចប់",
    listen: "ស្តាប់",
    stop: "ឈប់",
    typeOrSpeak: "សរសេរនៅទីនេះ ឬចុចមីក្រូហ្វូនហើយនិយាយ",
    send: "ផ្ញើ",
    riskLow: "កូនអ្នកមានសុវត្ថិភាពឥឡូវនេះ។",
    riskMedium: "ប្រុងប្រយ័ត្ន។ មើលថែកូនអ្នក។",
    riskHigh: "គ្រោះថ្នាក់។ ទុកកូននៅក្នុងផ្ទះឱ្យមានសុវត្ថិភាព។",
    riskCritical: "គ្រោះថ្នាក់ខ្លាំងណាស់! រកជំនួយឥឡូវនេះ។",
    heatLabel: "កំដៅ", heatDanger: "ក្តៅពេកសម្រាប់កុមារ។ ធ្វើឱ្យត្រជាក់ ផ្តល់ទឹក។", heatOk: "កំដៅមិនមានបញ្ហាឥឡូវនេះទេ។",
    sunLabel: "ព្រះអាទិត្យ", sunDanger: "កម្តៅថ្ងៃខ្លាំងណាស់។ ទុកកុមារនៅម្លប់។", sunOk: "ព្រះអាទិត្យមិនមានបញ្ហាទេ។",
    airLabel: "ខ្យល់", airDanger: "ខ្យល់អាក្រក់។ ទុកកុមារនៅក្នុងផ្ទះ។", airOk: "ខ្យល់ល្អឥឡូវនេះ។",
    rainLabel: "ភ្លៀង", rainDanger: "ភ្លៀងខ្លាំង។ ទឹកអាចឡើង។ ទៅកន្លែងខ្ពស់និងមានសុវត្ថិភាព។", rainOk: "ភ្លៀងមិនមានបញ្ហាទេ។",
  },
  lo: {
    isMyChildInDanger: "ລູກຂອງຂ້ອຍຢູ່ໃນອັນຕະລາຍບໍ?",
    myChildIsSick: "ລູກຂອງຂ້ອຍບໍ່ສະບາຍ",
    sendAPhoto: "ສົ່ງຮູບ",
    helpWithoutInternet: "ຄວາມຊ່ວຍເຫຼືອໂດຍບໍ່ມີອິນເຕີເນັດ",
    worldMap: "ແຜນທີ່ໂລກ",
    myChildren: "ລູກໆຂອງຂ້ອຍ",
    about: "ກ່ຽວກັບ",
    emergencyNow: "ສຸກເສີນ — ຊ່ວຍຂ້ອຍດຽວນີ້",
    emergencyNumbers: "ເບີໂທສຸກເສີນ",
    tapToCall: "ແຕະເບີເພື່ອໂທ",
    worksOffline: "ໃຊ້ໄດ້ໂດຍບໍ່ມີອິນເຕີເນັດ",
    callNow: "ໂທດຽວນີ້",
    tap: "ກົດ",
    heroTitle: "ປົກປ້ອງເດັກນ້ອຍຈາກອັນຕະລາຍຂອງອາກາດ",
    heroSub: "ນ້ຳຖ້ວມ, ຄວາມຮ້ອນ, ພາຍຸ, ອາກາດເປື້ອນ — ເບິ່ງວ່າລູກຂອງທ່ານປອດໄພບໍ ແລະ ຄວນເຮັດແນວໃດ. ໃນພາສາຂອງທ່ານ. ຟຣີ.",
    cardRiskDesc: "ເບິ່ງອັນຕະລາຍໃກ້ບ້ານທ່ານ ຕາມອາຍຸຂອງລູກ.",
    cardHealthDesc: "ບອກພວກເຮົາວ່າມີບັນຫາຫຍັງ — ເວົ້າ ຫຼື ຂຽນໃນພາສາຂອງທ່ານ.",
    cardPhotoDesc: "ຖ່າຍຮູບຜື່ນ, ບາດແຜ, ນ້ຳຖ້ວມ ຫຼື ຄວັນ. ພວກເຮົາເບິ່ງແລ້ວບອກວ່າຄວນເຮັດແນວໃດ.",
    cardMapDesc: "ເບິ່ງບ່ອນທີ່ອັນຕະລາຍຕໍ່ເດັກສູງໃນໂລກ.",
    open: "ເປີດ",
    statChildren: "ເດັກທີ່ປະເຊີນກັບອັນຕະລາຍອາກາດ 3+",
    statStudents: "ນັກຮຽນທີ່ການຮຽນຖືກລົບກວນໃນ 2024",
    statDisplaced: "ເດັກທີ່ຍ້າຍຖິ່ນທຸກມື້ຍ້ອນອາກາດ",
    statCountries: "ປະເທດ · 55 ພາສາ",
    whyTitle: "ເປັນຫຍັງພວກເຮົາສ້າງສິ່ງນີ້",
    storiesTitle: "ເຫດການສຸກເສີນຕົວຈິງ",
    storiesSub: "ຄອບຄົວໃຊ້ ClimaGuard ແນວໃດໃນເວລາຈຳເປັນ",
    countriesTitle: "ສ້າງເພື່ອເດັກທີ່ອ່ອນແອທີ່ສຸດຂອງໂລກ",
    countriesSub: "ທຸກປະເທດສ່ຽງສູງຂອງ UNICEF ໃນພາສາທ້ອງຖິ່ນ",
    moreCountries: "+51 ປະເທດອື່ນ",
    ctaTitle: "ເລີ່ມປົກປ້ອງລູກຂອງທ່ານດຽວນີ້",
    ctaSub: "ເລືອກປະເທດ ແລະ ອາຍຸລູກ — ຮັບຄຳຕອບ ແລະ ແຜນໃນພາສາຂອງທ່ານ.",
    chipNoAccount: "ບໍ່ຕ້ອງມີບັນຊີ",
    chipFree: "ຟຣີ 100%",
    chipLanguages: "55 ພາສາ",
    notMedical: "ບໍ່ແມ່ນການທົດແທນຄຳແນະນຳຂອງແພດ.",
    language: "ພາສາ",
    country: "ປະເທດ",
    childAge: "ອາຍຸເດັກ",
    checkNow: "ກວດເບິ່ງດຽວນີ້",
    checking: "ກຳລັງກວດ…",
    tapMicSpeak: "ແຕະໄມໂຄຣໂຟນ ແລ້ວເວົ້າໃນພາສາຂອງທ່ານ",
    recording: "ກຳລັງຟັງ… ແຕະໄມອີກຄັ້ງເມື່ອເວົ້າຈົບ",
    listen: "ຟັງ",
    stop: "ຢຸດ",
    typeOrSpeak: "ພິມທີ່ນີ້ ຫຼື ແຕະໄມແລ້ວເວົ້າ",
    send: "ສົ່ງ",
    riskLow: "ລູກຂອງທ່ານປອດໄພຢູ່ຕອນນີ້.",
    riskMedium: "ລະວັງ. ເບິ່ງແຍງລູກຂອງທ່ານ.",
    riskHigh: "ອັນຕະລາຍ. ໃຫ້ລູກຢູ່ໃນເຮືອນຢ່າງປອດໄພ.",
    riskCritical: "ອັນຕະລາຍຫຼາຍ! ຊອກຫາຄວາມຊ່ວຍເຫຼືອດຽວນີ້.",
    heatLabel: "ຄວາມຮ້ອນ", heatDanger: "ຮ້ອນເກີນໄປສຳລັບເດັກ. ເຮັດໃຫ້ເຢັນ, ໃຫ້ດື່ມນ້ຳ.", heatOk: "ຄວາມຮ້ອນບໍ່ເປັນບັນຫາຕອນນີ້.",
    sunLabel: "ແດດ", sunDanger: "ແດດແຮງຫຼາຍ. ໃຫ້ເດັກຢູ່ໃນຮົ່ມ.", sunOk: "ແດດບໍ່ເປັນບັນຫາຕອນນີ້.",
    airLabel: "ອາກາດ", airDanger: "ອາກາດເປື້ອນ. ໃຫ້ເດັກຢູ່ໃນເຮືອນ.", airOk: "ອາກາດດີຢູ່ຕອນນີ້.",
    rainLabel: "ຝົນ", rainDanger: "ຝົນຕົກໜັກ. ນ້ຳອາດຂຶ້ນ. ໄປບ່ອນສູງທີ່ປອດໄພ.", rainOk: "ຝົນບໍ່ເປັນບັນຫາຕອນນີ້.",
  },
  ko: {
    isMyChildInDanger: "우리 아이가 위험한가요?",
    myChildIsSick: "아이가 아파요",
    sendAPhoto: "사진 보내기",
    helpWithoutInternet: "인터넷 없이 도움받기",
    worldMap: "세계 지도",
    myChildren: "내 아이들",
    about: "소개",
    emergencyNow: "긴급 — 지금 도와주세요",
    emergencyNumbers: "긴급 전화번호",
    tapToCall: "번호를 누르면 전화가 걸립니다",
    worksOffline: "인터넷 없이도 작동합니다",
    callNow: "지금 전화하기",
    tap: "누르기",
    heroTitle: "기후 위험으로부터 아이들을 지킵니다",
    heroSub: "홍수, 폭염, 폭풍, 나쁜 공기 — 아이가 안전한지, 무엇을 해야 하는지 확인하세요. 당신의 언어로. 무료.",
    cardRiskDesc: "아이 나이에 맞춰 집 근처 위험을 확인하세요.",
    cardHealthDesc: "무엇이 문제인지 알려주세요 — 당신의 언어로 말하거나 쓰세요.",
    cardPhotoDesc: "발진, 상처, 홍수, 연기를 사진으로 찍으세요. 보고 무엇을 해야 할지 알려드립니다.",
    cardMapDesc: "전 세계에서 아이들에게 위험이 큰 곳을 확인하세요.",
    open: "열기",
    statChildren: "3개 이상의 기후 위험에 노출된 아이들",
    statStudents: "2024년 학업이 중단된 학생",
    statDisplaced: "기후로 매일 삶터를 잃는 아이들",
    statCountries: "개국 · 55개 언어 지원",
    whyTitle: "만든 이유",
    storiesTitle: "실제 긴급 상황",
    storiesSub: "위급한 순간 가족들이 ClimaGuard를 쓰는 방법",
    countriesTitle: "세계에서 가장 취약한 아이들을 위해 만들었습니다",
    countriesSub: "UNICEF 고위험 국가 전체, 현지 언어 지원",
    moreCountries: "+51개국 더",
    ctaTitle: "지금 아이 보호를 시작하세요",
    ctaSub: "국가와 아이 나이를 고르면 — 당신의 언어로 답과 계획을 받습니다.",
    chipNoAccount: "계정 불필요",
    chipFree: "100% 무료",
    chipLanguages: "55개 언어",
    notMedical: "의사의 진료를 대신하지 않습니다.",
    language: "언어",
    country: "국가",
    childAge: "아이 나이",
    checkNow: "지금 확인",
    checking: "확인 중…",
    tapMicSpeak: "마이크를 누르고 당신의 언어로 말하세요",
    recording: "듣고 있어요… 끝나면 마이크를 다시 누르세요",
    listen: "듣기",
    stop: "정지",
    typeOrSpeak: "여기에 입력하거나 마이크를 누르고 말하세요",
    send: "보내기",
    riskLow: "지금 아이는 안전합니다.",
    riskMedium: "조심하세요. 아이를 지켜보세요.",
    riskHigh: "위험합니다. 아이를 집 안에 안전하게 두세요.",
    riskCritical: "매우 위험합니다! 지금 도움을 받으세요.",
    heatLabel: "더위", heatDanger: "아이에게 너무 덥습니다. 시원하게 해주고 물을 주세요.", heatOk: "더위는 지금 괜찮습니다.",
    sunLabel: "햇볕", sunDanger: "햇볕이 매우 강합니다. 아이를 그늘에 두세요.", sunOk: "햇볕은 지금 괜찮습니다.",
    airLabel: "공기", airDanger: "공기가 나쁩니다. 아이를 실내에 두세요.", airOk: "공기는 지금 좋습니다.",
    rainLabel: "비", rainDanger: "폭우입니다. 물이 불어날 수 있어요. 높고 안전한 곳으로 가세요.", rainOk: "비는 지금 괜찮습니다.",
  },
  tr: {
    isMyChildInDanger: "Çocuğum tehlikede mi?",
    myChildIsSick: "Çocuğum hasta",
    sendAPhoto: "Fotoğraf gönder",
    helpWithoutInternet: "İnternetsiz yardım",
    worldMap: "Dünya haritası",
    myChildren: "Çocuklarım",
    about: "Hakkında",
    emergencyNow: "ACİL — hemen yardım edin",
    emergencyNumbers: "Acil numaralar",
    tapToCall: "Aramak için numaraya dokunun",
    worksOffline: "İnternetsiz de çalışır",
    callNow: "Hemen ara",
    tap: "DOKUN",
    heroTitle: "Çocukları hava tehlikelerinden koruyoruz",
    heroSub: "Sel, sıcak, fırtına, kirli hava — çocuğunuz güvende mi ve ne yapmalı, görün. Kendi dilinizde. Ücretsiz.",
    cardRiskDesc: "Evinizin yakınındaki tehlikeyi çocuğunuzun yaşına göre görün.",
    cardHealthDesc: "Sorunu anlatın — kendi dilinizde konuşun ya da yazın.",
    cardPhotoDesc: "Döküntü, yara, sel veya dumanın fotoğrafını çekin. Bakıp ne yapacağınızı söyleriz.",
    cardMapDesc: "Dünyada çocuklar için tehlikenin yüksek olduğu yerleri görün.",
    open: "Aç",
    statChildren: "3+ iklim tehlikesine maruz çocuk",
    statStudents: "2024'te eğitimi aksayan öğrenci",
    statDisplaced: "İklim yüzünden her gün yerinden olan çocuk",
    statCountries: "Ülke · 55 dil desteği",
    whyTitle: "Bunu neden yaptık",
    storiesTitle: "Gerçek acil durumlar",
    storiesSub: "Aileler zor anlarda ClimaGuard'ı nasıl kullanıyor",
    countriesTitle: "Dünyanın en savunmasız çocukları için yapıldı",
    countriesSub: "UNICEF'in tüm yüksek riskli ülkeleri, yerel dillerde",
    moreCountries: "+51 ülke daha",
    ctaTitle: "Çocuğunuzu korumaya hemen başlayın",
    ctaSub: "Ülkenizi ve çocuğunuzun yaşını seçin — kendi dilinizde yanıt ve plan alın.",
    chipNoAccount: "Hesap gerekmez",
    chipFree: "%100 ücretsiz",
    chipLanguages: "55 dil",
    notMedical: "Doktor tavsiyesinin yerini tutmaz.",
    language: "Dil",
    country: "Ülke",
    childAge: "Çocuğun yaşı",
    checkNow: "Şimdi kontrol et",
    checking: "Kontrol ediliyor…",
    tapMicSpeak: "Mikrofona dokunun, kendi dilinizde konuşun",
    recording: "Dinliyoruz… bitince mikrofona tekrar dokunun",
    listen: "Dinle",
    stop: "Durdur",
    typeOrSpeak: "Buraya yazın ya da mikrofona dokunup konuşun",
    send: "Gönder",
    riskLow: "Çocuğunuz şu an güvende.",
    riskMedium: "Dikkatli olun. Çocuğunuzu gözleyin.",
    riskHigh: "Tehlike. Çocuğunuzu evde, güvende tutun.",
    riskCritical: "ÇOK TEHLİKELİ! Hemen yardım alın.",
    heatLabel: "Sıcak", heatDanger: "Çocuklar için çok sıcak. Serinletin, su verin.", heatOk: "Sıcaklık şu an sorun değil.",
    sunLabel: "Güneş", sunDanger: "Güneş çok güçlü. Çocukları gölgede tutun.", sunOk: "Güneş şu an sorun değil.",
    airLabel: "Hava", airDanger: "Hava kirli. Çocukları içeride tutun.", airOk: "Hava şu an iyi.",
    rainLabel: "Yağmur", rainDanger: "Şiddetli yağmur. Su yükselebilir. Yüksek ve güvenli bir yere gidin.", rainOk: "Yağmur şu an sorun değil.",
  },
  ru: {
    isMyChildInDanger: "Мой ребёнок в опасности?",
    myChildIsSick: "Мой ребёнок болен",
    sendAPhoto: "Отправить фото",
    helpWithoutInternet: "Помощь без интернета",
    worldMap: "Карта мира",
    myChildren: "Мои дети",
    about: "О нас",
    emergencyNow: "ЭКСТРЕННО — помогите сейчас",
    emergencyNumbers: "Экстренные номера",
    tapToCall: "Нажмите на номер, чтобы позвонить",
    worksOffline: "Работает без интернета",
    callNow: "Позвонить сейчас",
    tap: "НАЖАТЬ",
    heroTitle: "Защищаем детей от опасной погоды",
    heroSub: "Наводнения, жара, штормы, грязный воздух — узнайте, в безопасности ли ваш ребёнок и что делать. На вашем языке. Бесплатно.",
    cardRiskDesc: "Узнайте об опасности рядом с домом с учётом возраста ребёнка.",
    cardHealthDesc: "Расскажите, что случилось — говорите или пишите на своём языке.",
    cardPhotoDesc: "Сфотографируйте сыпь, рану, наводнение или дым. Мы посмотрим и скажем, что делать.",
    cardMapDesc: "Посмотрите, где в мире детям грозит наибольшая опасность.",
    open: "Открыть",
    statChildren: "Детей подвержены 3+ климатическим угрозам",
    statStudents: "Учеников с прерванной учёбой в 2024",
    statDisplaced: "Детей ежедневно покидают дома из-за климата",
    statCountries: "Стран · поддержка 55 языков",
    whyTitle: "Почему мы это создали",
    storiesTitle: "Реальные чрезвычайные ситуации",
    storiesSub: "Как семьи используют ClimaGuard в трудную минуту",
    countriesTitle: "Создано для самых уязвимых детей мира",
    countriesSub: "Все страны высокого риска UNICEF, на местных языках",
    moreCountries: "+ ещё 51 страна",
    ctaTitle: "Начните защищать ребёнка прямо сейчас",
    ctaSub: "Выберите страну и возраст ребёнка — получите ответ и план на своём языке.",
    chipNoAccount: "Без аккаунта",
    chipFree: "Полностью бесплатно",
    chipLanguages: "55 языков",
    notMedical: "Не заменяет консультацию врача.",
    language: "Язык",
    country: "Страна",
    childAge: "Возраст ребёнка",
    checkNow: "Проверить сейчас",
    checking: "Проверяем…",
    tapMicSpeak: "Нажмите на микрофон и говорите на своём языке",
    recording: "Слушаем… нажмите на микрофон ещё раз, когда закончите",
    listen: "Слушать",
    stop: "Стоп",
    typeOrSpeak: "Пишите здесь или нажмите на микрофон и говорите",
    send: "Отправить",
    riskLow: "Ваш ребёнок сейчас в безопасности.",
    riskMedium: "Будьте осторожны. Следите за ребёнком.",
    riskHigh: "Опасность. Держите ребёнка дома, в безопасности.",
    riskCritical: "ОЧЕНЬ ОПАСНО! Немедленно ищите помощь.",
    heatLabel: "Жара", heatDanger: "Слишком жарко для детей. Охладите их, дайте воды.", heatOk: "Жара сейчас не опасна.",
    sunLabel: "Солнце", sunDanger: "Солнце очень сильное. Держите детей в тени.", sunOk: "Солнце сейчас не опасно.",
    airLabel: "Воздух", airDanger: "Воздух плохой. Держите детей дома.", airOk: "Воздух сейчас хороший.",
    rainLabel: "Дождь", rainDanger: "Сильный дождь. Вода может подняться. Идите на высокое безопасное место.", rainOk: "Дождь сейчас не опасен.",
  },
  fa: FA,
  prs: FA,
};

// Native (endonym) names so a parent can find their language even when the
// current UI language is unreadable to them — shown in the language picker.
export const NATIVE_LANGUAGE_NAMES: Record<string, string> = {
  bn: "বাংলা", hi: "हिन्दी", ur: "اردو", ar: "العربية", en: "English",
  fr: "Français", es: "Español", pt: "Português", sw: "Kiswahili",
  am: "አማርኛ", so: "Soomaali", ha: "Hausa", yo: "Yorùbá", ig: "Igbo",
  zu: "isiZulu", af: "Afrikaans", mg: "Malagasy", fil: "Filipino",
  id: "Bahasa Indonesia", ms: "Bahasa Melayu", vi: "Tiếng Việt", th: "ไทย",
  km: "ខ្មែរ", lo: "ລາວ", my: "မြန်မာ", tpi: "Tok Pisin", zh: "中文",
  ja: "日本語", ko: "한국어", ta: "தமிழ்", te: "తెలుగు", mr: "मराठी",
  gu: "ગુજરાતી", pa: "ਪੰਜਾਬੀ", kn: "ಕನ್ನಡ", ml: "മലയാളം", ne: "नेपाली",
  si: "සිංහල", fa: "فارسی", prs: "دری", ps: "پښتو", ku: "Kurdî",
  tk: "Türkmençe", tg: "Тоҷикӣ", ti: "ትግርኛ", rw: "Kinyarwanda",
  tr: "Türkçe", ru: "Русский", uk: "Українська", de: "Deutsch",
  it: "Italiano", nl: "Nederlands", pl: "Polski", el: "Ελληνικά", he: "עברית",
};

// Native (endonym) country names by country code, so a parent who cannot read
// English (Latin) still recognises their own country written in their own
// script. Only entries that differ from the English name are listed; everything
// else falls back to the English name (which is Latin and readable alongside the
// flag). See getNativeCountryName.
export const NATIVE_COUNTRY_NAMES: Record<string, string> = {
  BD: "বাংলাদেশ", IN: "भारत", PK: "پاکستان", NG: "Najeriya", EG: "مصر",
  SD: "السودان", ET: "ኢትዮጵያ", SO: "Soomaaliya", CF: "Centrafrique",
  MG: "Madagasikara", PH: "Pilipinas", PE: "Perú", PG: "Papua Niugini",
  MM: "မြန်မာ", AF: "افغانستان", TD: "Tchad", KH: "កម្ពុជា", MZ: "Moçambique",
  IR: "ایران", LA: "ລາວ", YE: "اليمن", IQ: "العراق", MR: "موريتانيا",
  TM: "Türkmenistan", CD: "RD Congo", ER: "ኤርትራ", SY: "سوريا", CM: "Cameroun",
  GN: "Guinée", LY: "ليبيا", TJ: "Тоҷикистон", HT: "Haïti", KP: "조선",
  GW: "Guiné-Bissau", GQ: "Guinea Ecuatorial", LB: "لبنان", KM: "جزر القمر",
};

/** Country name in its own language/script, falling back to the English name. */
export const getNativeCountryName = (code: string, english: string): string =>
  NATIVE_COUNTRY_NAMES[code] ?? english;

const RTL_LANGS = new Set(["ar", "ur", "fa", "prs", "ps", "he", "ku"]);

export const isRTL = (code: string): boolean => RTL_LANGS.has(code);

// Runtime-translated languages (fetched on demand for any of the 55 selectable
// languages not statically bundled, then cached). Populated by useUIStrings.
export const RUNTIME_UI: Record<string, UIStrings> = {};

/** True when a language's UI is available without a network fetch. */
export const hasStaticUI = (code: string): boolean =>
  code in UI_STRINGS || code in UI_STRINGS_AUTO || code in RUNTIME_UI;

/** UI strings for a language code: hand-written → auto-bundled → runtime → English. */
export const getUIStrings = (code: string): UIStrings =>
  UI_STRINGS[code] ?? UI_STRINGS_AUTO[code] ?? RUNTIME_UI[code] ?? UI_STRINGS.en;
